import type { CollectionSeoMap } from "./types";

/* ------------------------------------------------------------------
   FINISH facet SEO content. Keyed by slug (see libs/earringCategories.ts).
   Tier 1: gold-plated, anti-tarnish, oxidised, silver-tone.
   Tier 2: gold-tone, waterproof, enamel, pearl, crystal, cz,
           american-diamond, stone, kundan.
------------------------------------------------------------------- */

export const FINISH_SEO: CollectionSeoMap = {
  /* ===================== TIER 1 ===================== */
  "gold-plated": {
    tier: 1,
    metaTitle: "Gold Plated Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop gold plated earrings at Pearl Bloom — rich gold-tone shine over a durable core, anti-tarnish and skin-safe. A luxe gold look at everyday prices.",
    primaryKeyword: "gold plated earrings",
    secondaryKeywords: ["gold plated earrings for women", "gold plated studs", "gold plated hoops", "anti-tarnish gold plated"],
    h1: "Gold Plated Earrings for Women",
    lede: "Rich, micro-layered gold-tone shine over a durable core — a luxe look at an honest price.",
    heroAlt: "Pearl Bloom gold plated earrings showing warm gold-tone shine on a cream background",
    assignedBlog: "are-gold-plated-earrings-worth-it",
    intro: [
      "Gold plated earrings give you the warm, rich glow of gold without the fine-jewellery price tag. A fine layer of gold-tone plating is bonded over a durable base metal, then sealed with an anti-tarnish coating, so each pair looks luxe and keeps its shine through everyday wear. It is the smart way to get that solid-gold look for a fraction of the cost.",
      [
        "Plating works across every shape, which is why it is our most popular finish. You will find it on classic ",
        { text: "stud earrings", href: "/earrings/style/stud" },
        ", everyday ",
        { text: "hoops", href: "/earrings/style/hoop" },
        " and ornate festive designs alike. If you prefer a cooler look, compare it with bright ",
        { text: "silver-tone", href: "/earrings/finish/silver-tone" },
        " or the warm, consistent colour of our ",
        { text: "gold-tone", href: "/earrings/finish/gold-tone" },
        " range.",
      ],
      [
        "Because the finish is sealed and tarnish-resistant, gold plated earrings are ideal for ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        " — they hold their colour far better than untreated metal. To make them last even longer, keep them away from perfume, lotion and prolonged moisture, and store them dry. Our ",
        { text: "anti-tarnish", href: "/earrings/finish/anti-tarnish" },
        " collection explains the care in more detail.",
      ],
      "Gold plating is fashion jewellery, not solid gold — there is no hallmark and the pieces are not investment metal. What they are is genuinely good value: a premium gold look you can wear, restyle and refresh as often as you like. Wondering whether plated pairs are worth it and how long the shine lasts? Our gold-plated guide answers exactly that.",
    ],
    internalLinks: [
      { label: "Gold Tone", href: "/earrings/finish/gold-tone" },
      { label: "Silver Tone", href: "/earrings/finish/silver-tone" },
      { label: "Anti-Tarnish", href: "/earrings/finish/anti-tarnish" },
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Hoop Earrings", href: "/earrings/style/hoop" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
    ],
    faqs: [
      { q: "Are gold plated earrings real gold?", a: "No. Gold plated earrings have a thin layer of gold-tone plating over a base metal. They give a real-gold look but are fashion jewellery — not solid gold, and not hallmarked." },
      { q: "Do gold plated earrings fade or tarnish?", a: "All plating wears over time, but our gold plated earrings are sealed with an anti-tarnish coating that resists fading. Keeping them dry and away from perfume and lotion makes the shine last much longer." },
      { q: "How long do gold plated earrings last?", a: "With gentle care — stored dry, kept off skincare and sweat — a quality plated pair holds its colour for a long time. Because they are affordable, they are also easy to refresh when trends change." },
      { q: "Are gold plated earrings safe for sensitive ears?", a: "Yes. Our gold plated earrings use skin-safe, hypoallergenic metal, so they are comfortable for sensitive ears during daily wear." },
      { q: "Can I wear gold plated earrings in water?", a: "Brief contact with water is fine, but we recommend removing them before swimming or long showers and drying them afterwards to protect the plating. See our waterproof range for water-ready designs." },
      { q: "What is the difference between gold plated and gold tone?", a: "Gold plated has an actual layer of gold-tone metal bonded over a core, while gold tone refers to any finish that gives a gold colour. Both deliver a gold look at an affordable price." },
    ],
  },

  "anti-tarnish": {
    tier: 1,
    metaTitle: "Anti-Tarnish Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop anti-tarnish earrings at Pearl Bloom — shielded gold-tone that stays bright shower after shower, skin-safe and light. Set-and-forget shine awaits.",
    primaryKeyword: "anti tarnish earrings",
    secondaryKeywords: ["anti-tarnish earrings for women", "tarnish-free earrings", "waterproof earrings", "long lasting earrings"],
    h1: "Anti-Tarnish Earrings for Women",
    lede: "Shielded gold-tone that stays bright wear after wear — set-and-forget shine.",
    heroAlt: "Pearl Bloom anti-tarnish gold-tone earrings staying bright, on a cream background",
    assignedBlog: "anti-tarnish-waterproof-earrings-care",
    intro: [
      "Tarnish is the reason most fashion earrings end up at the back of the drawer — that dull, darkened look that creeps in after a few weeks. Anti-tarnish earrings are built to fight it. A protective coating shields the metal from the air, moisture and skin contact that cause oxidation, so your gold-tone stays gold for far longer. It is shine you can set and forget.",
      [
        "Anti-tarnish is less a single style and more a quality standard that runs across our catalogue — from ",
        { text: "gold-plated", href: "/earrings/finish/gold-plated" },
        " and ",
        { text: "gold-tone", href: "/earrings/finish/gold-tone" },
        " classics to everyday ",
        { text: "stud", href: "/earrings/style/stud" },
        " and ",
        { text: "hoop", href: "/earrings/style/hoop" },
        " designs. If you want pieces that handle sweat, rain and showers too, pair this with our ",
        { text: "waterproof", href: "/earrings/finish/waterproof" },
        " range.",
      ],
      [
        "This finish is made for people who actually wear their earrings — every day, in real life. That makes it the natural pick for ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        " and ",
        { text: "office wear", href: "/earrings/occasion/office-wear" },
        ", where you want a pair you can put on and forget about. The metal underneath is skin-safe and hypoallergenic, so comfort matches the convenience.",
      ],
      "No coating is completely indestructible, so a few small habits go a long way: keep the earrings dry, put them on after perfume and lotion rather than before, and wipe them with a soft cloth now and then. Do that, and anti-tarnish earrings will stay bright through season after season. Our care guide walks through exactly how the coatings work and how to make them last.",
    ],
    internalLinks: [
      { label: "Waterproof", href: "/earrings/finish/waterproof" },
      { label: "Gold Plated", href: "/earrings/finish/gold-plated" },
      { label: "Gold Tone", href: "/earrings/finish/gold-tone" },
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
      { label: "Office Wear", href: "/earrings/occasion/office-wear" },
    ],
    faqs: [
      { q: "Do anti-tarnish earrings really work?", a: "Yes. The protective coating slows the oxidation that causes tarnish, so anti-tarnish earrings stay bright much longer than untreated fashion jewellery — especially with simple care like keeping them dry." },
      { q: "Do anti-tarnish earrings ever tarnish?", a: "No coating lasts forever, but anti-tarnish earrings resist dulling far better than ordinary pieces. Avoiding perfume, lotion and prolonged moisture keeps them looking new for longer." },
      { q: "Are anti-tarnish earrings waterproof too?", a: "Anti-tarnish and waterproof are related but not identical. Anti-tarnish resists dulling; waterproof designs are built to handle sweat, rain and showers. Check our waterproof range for water-ready pairs." },
      { q: "Are anti-tarnish earrings good for sensitive ears?", a: "Yes. They use skin-safe, hypoallergenic metal, and the protective finish reduces skin contact with the base metal, which helps comfort for sensitive ears." },
      { q: "How should I care for anti-tarnish earrings?", a: "Keep them dry, store them in a pouch or box, put them on after applying perfume and skincare, and wipe gently with a soft cloth. These habits help the coating last as long as possible." },
      { q: "Are anti-tarnish earrings worth the money?", a: "For everyday wear, yes. They stay bright longer, look premium and remain affordable — so you replace them far less often than untreated fashion earrings." },
    ],
  },

  oxidised: {
    tier: 1,
    metaTitle: "Oxidised Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop oxidised earrings at Pearl Bloom — antique-finish silver-tone with heritage depth, lightweight and skin-safe. Pair boho and ethnic looks with ease.",
    primaryKeyword: "oxidised earrings",
    secondaryKeywords: ["oxidised earrings for women", "oxidised silver earrings", "german silver earrings", "oxidised jhumka"],
    h1: "Oxidised Earrings for Women",
    lede: "Antique-finish, darkened silver-tone with heritage depth and artisanal character.",
    heroAlt: "Pearl Bloom oxidised silver-tone earrings with antique finish on a cream background",
    assignedBlog: "oxidised-vs-gold-tone-vs-silver-tone",
    intro: [
      "Oxidised earrings are for anyone who loves a little shadow and soul in their jewellery. Instead of high shine, the metal is deliberately darkened to an antique, silver-grey finish with depth and texture — the moody, artisanal counterpart to bright gold. The look is rooted in Indian craft tradition, and it has become a modern favourite for boho, indie and fusion wardrobes.",
      [
        "This finish has real personality, which is why it suits expressive ethnic shapes so well. Oxidised ",
        { text: "jhumka", href: "/earrings/style/jhumka" },
        " and ",
        { text: "bali", href: "/earrings/style/bali" },
        " designs are especially striking, and the antique tone makes coloured stone and bead work pop. If you prefer a brighter, cleaner metal, compare it with our ",
        { text: "silver-tone", href: "/earrings/finish/silver-tone" },
        " range.",
      ],
      [
        "Oxidised earrings are wonderfully versatile across occasions. They bring instant character to ",
        { text: "festive wear", href: "/earrings/occasion/festive-wear" },
        " and ethnic looks, yet a smaller pair works just as well with a plain kurti or a denim-and-tee ",
        { text: "college", href: "/earrings/occasion/college-wear" },
        " outfit. The darker finish is also forgiving and low-maintenance day to day.",
      ],
      "A common question is whether oxidised earrings tarnish. The darkened look is part of the design rather than a flaw, and our pieces are sealed to hold that finish — they will not turn dull or patchy the way untreated metal can. The metal is skin-safe and hypoallergenic, and a soft dry wipe is usually all the care they need. To see how this finish compares with gold and bright silver, read our finishes guide.",
    ],
    internalLinks: [
      { label: "Silver Tone", href: "/earrings/finish/silver-tone" },
      { label: "Jhumka Earrings", href: "/earrings/style/jhumka" },
      { label: "Bali Earrings", href: "/earrings/style/bali" },
      { label: "Festive Wear", href: "/earrings/occasion/festive-wear" },
      { label: "College Wear", href: "/earrings/occasion/college-wear" },
      { label: "Kundan", href: "/earrings/finish/kundan" },
    ],
    faqs: [
      { q: "Do oxidised earrings tarnish?", a: "The dark, antique look is intentional, not tarnish. Our oxidised earrings are sealed to keep that finish, so they will not turn dull or patchy the way untreated metal does. A soft dry wipe keeps them looking their best." },
      { q: "What metal are oxidised earrings made from?", a: "They are made from skin-safe, hypoallergenic base metal with a darkened, antique silver-tone finish (often called German silver in style, though they are fashion jewellery, not pure silver)." },
      { q: "What outfits suit oxidised earrings?", a: "Oxidised earrings love ethnic, boho and fusion looks — kurtis, saris, cotton dresses and denim alike. The antique tone pairs especially well with coloured stones and bead work." },
      { q: "Are oxidised earrings good for sensitive ears?", a: "Yes. They use skin-safe, hypoallergenic metal, so they are comfortable for sensitive ears during long festive days and everyday wear." },
      { q: "How do I clean oxidised earrings?", a: "Wipe gently with a soft, dry cloth. Avoid harsh polishing or chemical cleaners, which can strip the antique finish. Keep them dry and away from perfume to maintain the look." },
      { q: "What is the difference between oxidised and silver-tone earrings?", a: "Oxidised earrings have a deliberately darkened, antique finish with shadow and depth, while silver-tone earrings are bright and high-shine. Choose oxidised for heritage character and silver-tone for a clean, modern look." },
    ],
  },

  "silver-tone": {
    tier: 1,
    metaTitle: "Silver Tone Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop silver tone earrings at Pearl Bloom — bright, cool-toned shine for a clean modern edge, anti-tarnish and skin-safe. A neutral that goes with all.",
    primaryKeyword: "silver tone earrings",
    secondaryKeywords: ["silver tone earrings for women", "silver colour earrings", "silver finish earrings"],
    h1: "Silver Tone Earrings for Women",
    lede: "Bright, cool-toned brilliance for a clean, contemporary edge.",
    heroAlt: "Pearl Bloom bright silver-tone earrings on a cream background",
    assignedBlog: "oxidised-vs-gold-tone-vs-silver-tone",
    intro: [
      "Silver tone earrings bring a bright, cool brilliance that feels effortlessly modern. Where gold reads warm and traditional, silver reads clean, crisp and contemporary — a true neutral that slips into almost any wardrobe. Pearl Bloom silver tone earrings deliver that high-shine, cool-spectrum look with an anti-tarnish finish, so the brightness lasts well beyond the first few wears.",
      [
        "Cool tones are quietly versatile. A pair of silver-tone ",
        { text: "studs", href: "/earrings/style/stud" },
        " or ",
        { text: "hoops", href: "/earrings/style/hoop" },
        " is a clean, minimal everyday choice, while ",
        { text: "crystal", href: "/earrings/finish/crystal" },
        " and ",
        { text: "CZ", href: "/earrings/finish/cz" },
        " set in silver tone reads especially icy and sparkly for evenings. If you love a darker, antique mood instead, see our ",
        { text: "oxidised", href: "/earrings/finish/oxidised" },
        " finish.",
      ],
      [
        "Silver tone is a natural fit for ",
        { text: "office wear", href: "/earrings/occasion/office-wear" },
        " and minimalist daily looks, and it pairs beautifully with greys, blues, blacks and cool pastels. It is also a smart match for silver-toned watches and accessories, keeping your metals coordinated.",
      ],
      "Like all our finishes, silver tone is fashion jewellery — it gives the look of polished silver without being sterling, and there is no hallmark. The upside is freedom: you can build a cool-toned earring wardrobe affordably and keep it bright with simple care. Store the earrings dry, keep them off perfume and lotion, and wipe gently to maintain the shine. To choose between cool silver, warm gold and antique oxidised, see our finishes comparison.",
    ],
    internalLinks: [
      { label: "Gold Tone", href: "/earrings/finish/gold-tone" },
      { label: "Oxidised", href: "/earrings/finish/oxidised" },
      { label: "Crystal Earrings", href: "/earrings/finish/crystal" },
      { label: "CZ Earrings", href: "/earrings/finish/cz" },
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Office Wear", href: "/earrings/occasion/office-wear" },
    ],
    faqs: [
      { q: "Are silver tone earrings real silver?", a: "No. Silver tone earrings give the look of polished silver but are fashion jewellery, not sterling silver, and are not hallmarked. They offer the cool-toned shine at an affordable price." },
      { q: "Do silver tone earrings tarnish?", a: "Our silver tone earrings have an anti-tarnish finish that keeps them bright far longer than untreated metal. Keeping them dry and away from perfume and lotion helps preserve the shine." },
      { q: "What colours and outfits suit silver tone earrings?", a: "Silver tone is a cool neutral that pairs well with greys, blues, blacks, whites and cool pastels, and coordinates with silver-toned watches and accessories for a put-together look." },
      { q: "Are silver tone earrings good for sensitive ears?", a: "Yes. They use skin-safe, hypoallergenic metal, making them comfortable for sensitive ears in daily and office wear." },
      { q: "Should I choose gold tone or silver tone?", a: "It is mostly about preference and wardrobe. Gold tone reads warm and traditional; silver tone reads cool and modern. Many people own both and match them to outfit and metal accessories." },
      { q: "How do I keep silver tone earrings shiny?", a: "Store them dry in a pouch or box, apply perfume and skincare before putting them on, and wipe occasionally with a soft cloth to maintain the bright, cool finish." },
    ],
  },

  /* ===================== TIER 2 ===================== */
  "gold-tone": {
    tier: 2,
    metaTitle: "Gold Tone Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop gold tone earrings at Pearl Bloom — warm, flattering gold colour that lasts, anti-tarnish and skin-safe. Everyday gold shine without the price tag.",
    primaryKeyword: "gold tone earrings",
    secondaryKeywords: ["gold tone earrings for women", "gold colour earrings", "gold finish earrings"],
    h1: "Gold Tone Earrings for Women",
    lede: "Warm, luminous gold colour that lasts — without the precious-metal price.",
    heroAlt: "Pearl Bloom warm gold-tone earrings on a cream background",
    assignedBlog: "oxidised-vs-gold-tone-vs-silver-tone",
    intro: [
      "Gold tone earrings give you the warm, luminous glow of gold without the precious-metal price tag. The colour is rich and flattering across skin tones, and because it is sealed with an anti-tarnish finish, that warmth lasts well beyond the first few wears. It is the everyday gold look, made affordable.",
      [
        "Closely related to ",
        { text: "gold-plated", href: "/earrings/finish/gold-plated" },
        " — the practical difference is small for most shoppers — gold tone is the most versatile finish in any wardrobe, pairing with both Indian and Western outfits. Prefer something cooler? Compare it with bright ",
        { text: "silver-tone", href: "/earrings/finish/silver-tone" },
        ". For pieces that hold their colour through constant use, look for the ",
        { text: "anti-tarnish", href: "/earrings/finish/anti-tarnish" },
        " range, ideal for ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        ". Keep them dry and off perfume to make the shine last.",
      ],
    ],
    internalLinks: [
      { label: "Gold Plated", href: "/earrings/finish/gold-plated" },
      { label: "Silver Tone", href: "/earrings/finish/silver-tone" },
      { label: "Anti-Tarnish", href: "/earrings/finish/anti-tarnish" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
    ],
    faqs: [
      { q: "Are gold tone earrings real gold?", a: "No. Gold tone earrings give the warm colour of gold but are fashion jewellery, not solid gold, and are not hallmarked. They offer the gold look at an affordable price." },
      { q: "What is the difference between gold tone and gold plated?", a: "Gold plated has an actual bonded layer of gold-tone metal over a core, while gold tone refers to any finish that gives a gold colour. For most shoppers the everyday difference is small." },
      { q: "Do gold tone earrings tarnish?", a: "Our gold tone earrings have an anti-tarnish finish that resists dulling. Keeping them dry and away from perfume and lotion helps the colour last much longer." },
      { q: "Are gold tone earrings safe for sensitive ears?", a: "Yes. They use skin-safe, hypoallergenic metal, so they are comfortable for sensitive ears during daily wear." },
    ],
  },

  waterproof: {
    tier: 2,
    metaTitle: "Waterproof Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop waterproof earrings at Pearl Bloom — sweat-, shower- and swim-safe gold-tone that resists fading, skin-safe and light. Wear them everywhere, daily.",
    primaryKeyword: "waterproof earrings",
    secondaryKeywords: ["waterproof earrings for women", "sweat proof earrings", "shower-safe earrings", "gym earrings"],
    h1: "Waterproof Earrings for Women",
    lede: "Sweat-, shower- and swim-safe coatings built for real life.",
    heroAlt: "Pearl Bloom waterproof gold-tone earrings with water droplets on a cream background",
    assignedBlog: "anti-tarnish-waterproof-earrings-care",
    intro: [
      "Waterproof earrings are made for people who do not want to take their jewellery off all the time. Sealed to handle sweat, rain and splashes, they are built for the gym, the beach and the monsoon — so you can wear them through your workout, your commute and your day without a second thought.",
      [
        "Waterproof and ",
        { text: "anti-tarnish", href: "/earrings/finish/anti-tarnish" },
        " go hand in hand: the same protective sealing that fights water also helps the ",
        { text: "gold-plated", href: "/earrings/finish/gold-plated" },
        " colour stay bright. That makes these the ultimate low-maintenance pick for ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        ", and they hold up just as well for ",
        { text: "party", href: "/earrings/occasion/party-wear" },
        " nights. For very long swims or hot showers, removing heavily embellished pairs still helps them last longest.",
      ],
    ],
    internalLinks: [
      { label: "Anti-Tarnish", href: "/earrings/finish/anti-tarnish" },
      { label: "Gold Plated", href: "/earrings/finish/gold-plated" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
      { label: "Party Wear", href: "/earrings/occasion/party-wear" },
    ],
    faqs: [
      { q: "Can I really shower and swim with waterproof earrings?", a: "Yes, they handle sweat, rain and splashes well. For long, hot showers or chlorinated pools, it is still best to remove embellished or stone-set pairs to maximise their lifespan." },
      { q: "What is the difference between waterproof and anti-tarnish?", a: "Anti-tarnish resists dulling over time, while waterproof is specifically built to handle water, sweat and humidity. Many Pearl Bloom pairs are both." },
      { q: "Are waterproof earrings good for the gym?", a: "Definitely. They are designed to withstand sweat and moisture, so they are ideal for workouts and active days without fading." },
      { q: "Are waterproof earrings skin-safe?", a: "Yes. They use skin-safe, hypoallergenic metal with a sealed finish, which suits sensitive ears and everyday active wear." },
    ],
  },

  enamel: {
    tier: 2,
    metaTitle: "Enamel Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop enamel earrings at Pearl Bloom — glossy, chip-resistant colour fused to skin-safe metal, light and anti-tarnish. Add a vivid pop to any outfit.",
    primaryKeyword: "enamel earrings",
    secondaryKeywords: ["enamel earrings for women", "colourful earrings", "meenakari earrings"],
    h1: "Enamel Earrings for Women",
    lede: "Glossy, hand-filled colour fused to metal — vivid and durable.",
    heroAlt: "Pearl Bloom colourful enamel earrings on a cream background",
    assignedBlog: "oxidised-vs-gold-tone-vs-silver-tone",
    intro: [
      "Enamel earrings bring colour to the party. Glossy, hand-filled enamel is fused to metal for playful, vivid pops of colour that resist chipping — a fun, expressive alternative to plain metal finishes. Whether you love bold brights or soft pastels, enamel lets your earrings match your mood and your outfit.",
      [
        "The colour reads beautifully against warm ",
        { text: "gold-tone", href: "/earrings/finish/gold-tone" },
        " and pairs naturally with sparkly ",
        { text: "crystal", href: "/earrings/finish/crystal" },
        " accents. Enamel earrings are a favourite for ",
        { text: "college wear", href: "/earrings/occasion/college-wear" },
        " and fun ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        ", where personality is the point. Skin-safe and anti-tarnish, they keep their gloss with simple care — just keep them dry and avoid harsh knocks.",
      ],
    ],
    internalLinks: [
      { label: "Gold Tone", href: "/earrings/finish/gold-tone" },
      { label: "Crystal Earrings", href: "/earrings/finish/crystal" },
      { label: "College Wear", href: "/earrings/occasion/college-wear" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
    ],
    faqs: [
      { q: "Do enamel earrings chip easily?", a: "Quality enamel is fused to the metal to resist chipping. Avoiding hard knocks and storing them carefully keeps the glossy colour looking fresh for a long time." },
      { q: "What outfits suit enamel earrings?", a: "Enamel adds a vivid pop, so it works beautifully with simple or neutral outfits, casual and college looks, and any time you want a fun splash of colour." },
      { q: "Are enamel earrings skin-safe?", a: "Yes. They use skin-safe, hypoallergenic metal with an anti-tarnish finish, so they are comfortable for everyday wear." },
      { q: "How do I care for enamel earrings?", a: "Keep them dry, avoid hard impacts, and wipe gently with a soft cloth. Avoid harsh chemical cleaners, which can dull the glossy enamel surface." },
    ],
  },

  pearl: {
    tier: 2,
    metaTitle: "Pearl Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop pearl earrings at Pearl Bloom — soft-lustre faux and shell pearls, lightweight and skin-safe. Timeless elegance for work and weddings alike.",
    primaryKeyword: "pearl earrings",
    secondaryKeywords: ["pearl earrings for women", "pearl studs", "pearl drop earrings", "bridal pearl earrings"],
    h1: "Pearl Earrings for Women",
    lede: "Soft-lustre faux and shell pearls — timeless femininity for any moment.",
    heroAlt: "Pearl Bloom faux pearl earrings with soft lustre on a cream background",
    assignedBlog: "anti-tarnish-waterproof-earrings-care",
    intro: [
      "Few earrings are as timeless as pearls. Their soft, natural lustre brings instant femininity and elegance, working as beautifully with office tailoring as with a bridal lehenga. Pearl Bloom pearl earrings use carefully selected faux and shell pearls for that classic glow at an affordable, everyday price.",
      [
        "Pearls are wonderfully versatile. A simple pearl ",
        { text: "stud", href: "/earrings/style/stud" },
        " is a refined choice for ",
        { text: "office wear", href: "/earrings/occasion/office-wear" },
        ", while pearl ",
        { text: "drops", href: "/earrings/style/drop" },
        " add soft romance for ",
        { text: "bridal", href: "/earrings/occasion/bridal" },
        " and wedding looks. Pearls prefer gentle care: keep them dry, away from perfume and lotion, and wipe softly so the lustre stays beautiful for years.",
      ],
    ],
    internalLinks: [
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Drop Earrings", href: "/earrings/style/drop" },
      { label: "Bridal", href: "/earrings/occasion/bridal" },
      { label: "Office Wear", href: "/earrings/occasion/office-wear" },
    ],
    faqs: [
      { q: "Are Pearl Bloom pearl earrings real pearls?", a: "They use high-quality faux and shell pearls chosen for a soft, natural lustre. They give the timeless pearl look as affordable fashion jewellery rather than expensive natural pearls." },
      { q: "What occasions suit pearl earrings?", a: "Pearls are remarkably versatile — pearl studs are perfect for the office, while pearl drops are elegant for weddings, bridal looks and evenings out." },
      { q: "How do I care for pearl earrings?", a: "Pearls are delicate, so keep them dry, put them on after perfume and skincare, and wipe gently with a soft cloth. Avoid water and chemicals to protect the lustre." },
      { q: "Are pearl earrings good for sensitive ears?", a: "Yes. The fittings use skin-safe, hypoallergenic metal, so they are comfortable for sensitive ears." },
    ],
  },

  crystal: {
    tier: 2,
    metaTitle: "Crystal Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop crystal earrings at Pearl Bloom — faceted stones cut for maximum sparkle, lightweight and skin-safe. The quick way to add shine to any look.",
    primaryKeyword: "crystal earrings",
    secondaryKeywords: ["crystal earrings for women", "crystal studs", "sparkly earrings", "party crystal earrings"],
    h1: "Crystal Earrings for Women",
    lede: "Faceted stones cut to throw maximum sparkle under any light.",
    heroAlt: "Pearl Bloom sparkling crystal earrings catching the light on a cream background",
    assignedBlog: "oxidised-vs-gold-tone-vs-silver-tone",
    intro: [
      "Crystal earrings are the fastest way to add sparkle. Faceted crystals are cut to throw maximum fire under any light, so even a small pair brings instant glamour — no carats required. Pearl Bloom crystal earrings deliver that dazzle in lightweight, skin-safe designs you can wear all evening.",
      [
        "For even more brilliance, compare crystals with diamond-bright ",
        { text: "CZ", href: "/earrings/finish/cz" },
        " and premium ",
        { text: "American Diamond", href: "/earrings/finish/american-diamond" },
        " stones. Crystal ",
        { text: "studs", href: "/earrings/style/stud" },
        " are an easy everyday sparkle, while larger crystal designs are made for ",
        { text: "party wear", href: "/earrings/occasion/party-wear" },
        ". Keep them dry and store them flat so every facet keeps catching the light.",
      ],
    ],
    internalLinks: [
      { label: "CZ Earrings", href: "/earrings/finish/cz" },
      { label: "American Diamond", href: "/earrings/finish/american-diamond" },
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Party Wear", href: "/earrings/occasion/party-wear" },
    ],
    faqs: [
      { q: "Are crystal earrings the same as diamonds?", a: "No. Crystal earrings use faceted glass crystals cut for sparkle. They give a brilliant, light-catching look as affordable fashion jewellery, not real diamonds." },
      { q: "What is the difference between crystal and CZ earrings?", a: "Crystals are faceted glass that sparkle brightly, while CZ (cubic zirconia) is a stone with a clearer, more diamond-like brilliance. Both add affordable shine." },
      { q: "Are crystal earrings good for parties?", a: "Yes. Their light-catching sparkle makes crystal earrings ideal for parties and evenings, while smaller crystal studs work for everyday shine." },
      { q: "Are crystal earrings skin-safe?", a: "Yes. The fittings use skin-safe, hypoallergenic metal with an anti-tarnish finish, so they are comfortable for sensitive ears." },
    ],
  },

  cz: {
    tier: 2,
    metaTitle: "CZ Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop CZ earrings at Pearl Bloom — cubic zirconia with diamond-bright clarity, lightweight and skin-safe. Luxe sparkle at honestly affordable prices.",
    primaryKeyword: "CZ earrings",
    secondaryKeywords: ["cubic zirconia earrings", "CZ studs", "CZ earrings for women", "sparkly stud earrings"],
    h1: "CZ Earrings for Women",
    lede: "Cubic-zirconia clarity with a dazzling, diamond-bright return of light.",
    heroAlt: "Pearl Bloom CZ cubic zirconia stud earrings sparkling on a cream background",
    assignedBlog: "oxidised-vs-gold-tone-vs-silver-tone",
    intro: [
      "CZ earrings deliver luxe, diamond-bright sparkle honestly and affordably. Cubic zirconia stones are prized for their clarity and dazzling return of light, giving the look of fine jewellery at fashion-jewellery prices. Pearl Bloom CZ earrings set those stones with care for maximum brilliance and secure, comfortable wear.",
      [
        "A CZ ",
        { text: "stud", href: "/earrings/style/stud" },
        " is a timeless everyday sparkle that suits almost any outfit, while bolder CZ designs shine at ",
        { text: "party wear", href: "/earrings/occasion/party-wear" },
        ". For more sparkle options, compare CZ with faceted ",
        { text: "crystal", href: "/earrings/finish/crystal" },
        " and premium ",
        { text: "American Diamond", href: "/earrings/finish/american-diamond" },
        " stones. Keep them dry and wipe gently so the stones keep their clarity.",
      ],
    ],
    internalLinks: [
      { label: "Crystal Earrings", href: "/earrings/finish/crystal" },
      { label: "American Diamond", href: "/earrings/finish/american-diamond" },
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Party Wear", href: "/earrings/occasion/party-wear" },
    ],
    faqs: [
      { q: "What are CZ earrings?", a: "CZ stands for cubic zirconia — a stone known for its diamond-bright clarity and sparkle. CZ earrings give a luxe, diamond-like look as affordable fashion jewellery." },
      { q: "Are CZ earrings real diamonds?", a: "No. Cubic zirconia is a diamond simulant, not a real diamond. It offers brilliant sparkle and clarity at a fraction of the price." },
      { q: "Are CZ earrings good for everyday wear?", a: "Yes. A simple CZ stud is a versatile everyday sparkle, while larger CZ designs are perfect for parties and special occasions." },
      { q: "Are CZ earrings skin-safe?", a: "Yes. They use skin-safe, hypoallergenic metal with an anti-tarnish finish, so they suit sensitive ears." },
    ],
  },

  "american-diamond": {
    tier: 2,
    metaTitle: "American Diamond Earrings | Pearl Bloom",
    metaDescription:
      "Shop American Diamond earrings at Pearl Bloom — premium AD stones set for red-carpet glitter, light and skin-safe. Brilliant shine, beautifully affordable.",
    primaryKeyword: "American Diamond earrings",
    secondaryKeywords: ["AD earrings", "american diamond earrings for women", "AD stud earrings", "ad jhumka"],
    h1: "American Diamond Earrings for Women",
    lede: "Premium AD stones set for red-carpet glitter, every day.",
    heroAlt: "Pearl Bloom American Diamond earrings with brilliant stones on a cream background",
    assignedBlog: "oxidised-vs-gold-tone-vs-silver-tone",
    intro: [
      "American Diamond (AD) earrings bring serious sparkle. Premium AD stones are set with jeweller-like precision for a brilliant, red-carpet glitter that looks far more expensive than it is. Pearl Bloom American Diamond earrings give you that maximum-shine moment, beautifully affordable and comfortably light.",
      [
        "AD stones are popular across both modern and traditional designs — from dazzling ",
        { text: "studs", href: "/earrings/style/stud" },
        " to ornate ",
        { text: "chandbali", href: "/earrings/style/chandbali" },
        " pieces. They are a favourite for ",
        { text: "wedding wear", href: "/earrings/occasion/wedding-wear" },
        " and ",
        { text: "bridal", href: "/earrings/occasion/bridal" },
        " looks that need to photograph beautifully. For other sparkle, compare AD with ",
        { text: "CZ", href: "/earrings/finish/cz" },
        " stones. Keep them dry and stored flat to protect every setting.",
      ],
    ],
    internalLinks: [
      { label: "CZ Earrings", href: "/earrings/finish/cz" },
      { label: "Crystal Earrings", href: "/earrings/finish/crystal" },
      { label: "Chandbali Earrings", href: "/earrings/style/chandbali" },
      { label: "Wedding Wear", href: "/earrings/occasion/wedding-wear" },
      { label: "Bridal", href: "/earrings/occasion/bridal" },
    ],
    faqs: [
      { q: "What are American Diamond earrings?", a: "American Diamond (AD) earrings use premium diamond-simulant stones set for maximum brilliance. They give a high-sparkle, fine-jewellery look as affordable fashion jewellery." },
      { q: "Are American Diamonds real diamonds?", a: "No. American Diamond is a high-quality diamond simulant, not a real diamond. It offers brilliant, red-carpet sparkle at a fraction of the cost." },
      { q: "Are AD earrings good for weddings?", a: "Yes. Their brilliant sparkle photographs beautifully, making AD earrings — especially studs and chandbalis — a popular choice for weddings and bridal looks." },
      { q: "Are American Diamond earrings skin-safe?", a: "Yes. They use skin-safe, hypoallergenic metal with an anti-tarnish finish, so they are comfortable for sensitive ears." },
    ],
  },

  stone: {
    tier: 2,
    metaTitle: "Stone Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop stone earrings at Pearl Bloom — jewel-toned colour in ruby red, emerald green and more, light and skin-safe. Add a pop of colour to any outfit.",
    primaryKeyword: "stone earrings",
    secondaryKeywords: ["stone earrings for women", "coloured stone earrings", "green stone earrings", "ruby stone earrings"],
    h1: "Stone Earrings for Women",
    lede: "Jewel-toned colour — ruby reds, emerald greens, sapphire blues.",
    heroAlt: "Pearl Bloom coloured stone earrings in jewel tones on a cream background",
    assignedBlog: "oxidised-vs-gold-tone-vs-silver-tone",
    intro: [
      "Stone earrings are the easiest way to add a pop of colour. Jewel-toned stones — ruby reds, emerald greens, sapphire blues and more — bring richness and personality that plain metal cannot, and let you tie your earrings straight to your outfit. Pearl Bloom stone earrings are hand-set for secure, lasting wear.",
      [
        "Coloured stones look stunning in ",
        { text: "drop", href: "/earrings/style/drop" },
        " designs and pair naturally with sparkly ",
        { text: "crystal", href: "/earrings/finish/crystal" },
        " accents. They are a go-to for ",
        { text: "party wear", href: "/earrings/occasion/party-wear" },
        " and ",
        { text: "festive", href: "/earrings/occasion/festive-wear" },
        " looks, where colour really shines. Keep them dry and store them flat so the stones stay secure and vivid.",
      ],
    ],
    internalLinks: [
      { label: "Crystal Earrings", href: "/earrings/finish/crystal" },
      { label: "Drop Earrings", href: "/earrings/style/drop" },
      { label: "Party Wear", href: "/earrings/occasion/party-wear" },
      { label: "Festive Wear", href: "/earrings/occasion/festive-wear" },
    ],
    faqs: [
      { q: "Are the stones in these earrings real gemstones?", a: "No. Stone earrings use coloured glass and simulant stones for vivid jewel tones. They are affordable fashion jewellery designed to add colour, not real precious gemstones." },
      { q: "What colours do stone earrings come in?", a: "Expect jewel tones like ruby red, emerald green and sapphire blue, among others, so you can match or contrast with your outfit." },
      { q: "What outfits suit coloured stone earrings?", a: "They are perfect for adding a pop of colour to parties and festive looks, and for coordinating with the tones in a sari, suit or dress." },
      { q: "Are stone earrings skin-safe and anti-tarnish?", a: "Yes. They use skin-safe, hypoallergenic metal with an anti-tarnish finish, and the stones are hand-set for secure, lasting wear." },
    ],
  },

  kundan: {
    tier: 2,
    metaTitle: "Kundan Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop kundan earrings at Pearl Bloom — regal glass-set gold-tone craft for festive and bridal looks, light and skin-safe. Heritage grandeur, made easy.",
    primaryKeyword: "kundan earrings",
    secondaryKeywords: ["kundan earrings for women", "bridal kundan", "kundan jhumka", "festive kundan earrings"],
    h1: "Kundan Earrings for Women",
    lede: "The ancient art of glass-set gold — regal Indian craftsmanship.",
    heroAlt: "Pearl Bloom kundan earrings with glass-set gold-tone detailing on a cream background",
    assignedBlog: "how-to-style-jhumkas-and-chandbalis",
    intro: [
      "Kundan earrings carry centuries of Indian craft. The traditional kundan technique sets glass stones into gold-tone metal, layered for a rich, regal effect that has adorned royalty and brides for generations. Pearl Bloom kundan earrings recreate that heritage grandeur in a lightweight, hypoallergenic build that is easy to wear.",
      [
        "Kundan is made for celebration. It shines in traditional shapes like the ",
        { text: "jhumka", href: "/earrings/style/jhumka" },
        " and ",
        { text: "chandbali", href: "/earrings/style/chandbali" },
        ", and is a classic for ",
        { text: "bridal", href: "/earrings/occasion/bridal" },
        ", ",
        { text: "wedding", href: "/earrings/occasion/wedding-wear" },
        " and ",
        { text: "festive wear", href: "/earrings/occasion/festive-wear" },
        ". Store kundan pieces dry and flat, away from perfume, to protect the delicate settings between occasions.",
      ],
    ],
    internalLinks: [
      { label: "Jhumka Earrings", href: "/earrings/style/jhumka" },
      { label: "Chandbali Earrings", href: "/earrings/style/chandbali" },
      { label: "Bridal", href: "/earrings/occasion/bridal" },
      { label: "Wedding Wear", href: "/earrings/occasion/wedding-wear" },
      { label: "Festive Wear", href: "/earrings/occasion/festive-wear" },
    ],
    faqs: [
      { q: "What are kundan earrings?", a: "Kundan earrings use a traditional Indian technique of setting glass stones into gold-tone metal, creating a layered, regal look popular for festive and bridal jewellery." },
      { q: "Are kundan earrings good for weddings?", a: "Yes. Kundan's rich, traditional grandeur makes it a classic choice for brides and wedding guests, especially in jhumka and chandbali styles." },
      { q: "Are kundan earrings heavy?", a: "Traditional kundan can be heavy, but Pearl Bloom kundan earrings are built lightweight so they keep the regal look while staying comfortable through long functions." },
      { q: "How do I care for kundan earrings?", a: "Keep them dry and away from perfume and water, store them flat in a box, and handle gently to protect the delicate glass settings." },
    ],
  },
};
