import type { CollectionSeoMap } from "./types";

/* ------------------------------------------------------------------
   OCCASION facet SEO content. Keyed by slug (see libs/earringCategories.ts).
   Tier 1: daily-wear, office-wear, party-wear, wedding-wear.
   Tier 2: festive-wear, bridal, college-wear, gift, set.
------------------------------------------------------------------- */

export const OCCASION_SEO: CollectionSeoMap = {
  /* ===================== TIER 1 ===================== */
  "daily-wear": {
    tier: 1,
    metaTitle: "Daily Wear Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop daily wear earrings at Pearl Bloom — ultralight studs and hoops for all-day comfort, anti-tarnish and skin-safe. So light you'll forget them on.",
    primaryKeyword: "daily wear earrings",
    secondaryKeywords: ["daily wear earrings for women", "everyday earrings", "lightweight earrings", "office daily earrings"],
    h1: "Daily Wear Earrings for Women",
    lede: "Ultralight studs and hoops built for all-day, every-day comfort.",
    heroAlt: "Pearl Bloom lightweight daily wear gold-tone earrings on a cream background",
    assignedBlog: "earrings-for-every-occasion",
    intro: [
      "The best daily wear earrings are the ones you stop noticing — light, secure and comfortable enough to wear from morning to night without a second thought. Pearl Bloom daily wear earrings are designed exactly that way: feather-light builds, smooth posts and an anti-tarnish finish that survives real life, from the commute to the gym to dinner.",
      [
        "For everyday, simple wins. Classic ",
        { text: "stud earrings", href: "/earrings/style/stud" },
        " and slim ",
        { text: "hoop earrings", href: "/earrings/style/hoop" },
        " go with everything, while petite ",
        { text: "huggies", href: "/earrings/style/huggies" },
        " are perfect for a stacked, low-key ear. A warm ",
        { text: "gold-tone", href: "/earrings/finish/gold-tone" },
        " or cool silver-tone finish keeps them easy to match with any outfit.",
      ],
      [
        "Daily wear overlaps neatly with the workday, so many of these pieces double as ",
        { text: "office wear", href: "/earrings/occasion/office-wear" },
        " too. The key is comfort and durability: because you will wear them constantly, the ",
        { text: "anti-tarnish", href: "/earrings/finish/anti-tarnish" },
        " coating and skin-safe metal really earn their keep, resisting dullness and keeping sensitive ears happy.",
      ],
      "Affordable pricing means you can keep a few go-to pairs on rotation — one gold, one silver, one with a little sparkle — and never overthink your accessories again. To keep them at their best, put them on after perfume and skincare, store them dry, and give them an occasional wipe. For a full breakdown of what to wear when, see our earrings-for-every-occasion guide.",
    ],
    internalLinks: [
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Hoop Earrings", href: "/earrings/style/hoop" },
      { label: "Huggie Earrings", href: "/earrings/style/huggies" },
      { label: "Anti-Tarnish", href: "/earrings/finish/anti-tarnish" },
      { label: "Office Wear", href: "/earrings/occasion/office-wear" },
      { label: "Gold Tone", href: "/earrings/finish/gold-tone" },
    ],
    faqs: [
      { q: "What are the best earrings for daily wear?", a: "Lightweight studs, slim hoops and huggies are the best daily wear earrings — they are comfortable, secure and go with everything. An anti-tarnish finish keeps them looking new despite constant wear." },
      { q: "Are daily wear earrings comfortable enough to sleep in?", a: "Many plain, lightweight studs are comfortable enough to leave in, but for hygiene and longevity it is best to remove stone-set pairs at night and keep them dry." },
      { q: "Will daily wear earrings tarnish with constant use?", a: "They resist it. Our daily wear earrings use anti-tarnish coatings, and simple care — keeping them dry and off perfume and lotion — keeps the shine going for a long time." },
      { q: "Are these earrings okay for sensitive ears?", a: "Yes. They use skin-safe, hypoallergenic metal with smooth posts, so they suit sensitive ears even with all-day, every-day wear." },
      { q: "Can I wear daily wear earrings to the office?", a: "Definitely. Most daily wear styles are minimal and polished enough to double as office wear, so a single pair covers both." },
      { q: "How many pairs of daily earrings should I own?", a: "A small rotation works well — for example one gold-tone, one silver-tone and one with a little sparkle — so you always have a pair to match your outfit without overthinking it." },
    ],
  },

  "office-wear": {
    tier: 1,
    metaTitle: "Office Wear Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop office wear earrings at Pearl Bloom — refined, minimalist gold-tone classics for the workday, light and anti-tarnish. Polished from 9 to 9.",
    primaryKeyword: "office wear earrings",
    secondaryKeywords: ["office wear earrings for women", "formal earrings", "work earrings", "minimalist earrings"],
    h1: "Office Wear Earrings for Women",
    lede: "Refined, minimalist classics that anchor your weekday wardrobe.",
    heroAlt: "Pearl Bloom minimalist gold-tone office wear earrings on a cream background",
    assignedBlog: "earrings-for-every-occasion",
    intro: [
      "Office wear earrings have one job: to look polished without pulling focus. Pearl Bloom office wear earrings are refined and minimalist by design — clean shapes and quiet shine that read professional in meetings, on camera and across back-to-back days. They are light enough to forget and smart enough to elevate everything from a crisp shirt to a sari.",
      [
        "For work, restraint is the look. Small ",
        { text: "stud earrings", href: "/earrings/style/stud" },
        ", neat ",
        { text: "huggies", href: "/earrings/style/huggies" },
        " and slim ",
        { text: "hoops", href: "/earrings/style/hoop" },
        " are the dependable trio. A warm ",
        { text: "gold-tone", href: "/earrings/finish/gold-tone" },
        " finish feels classic, while ",
        { text: "pearl", href: "/earrings/finish/pearl" },
        " studs add a soft, timeless touch that suits formal settings.",
      ],
      [
        "The same understated pieces transition easily into evening, overlapping with ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        " and even low-key ",
        { text: "party wear", href: "/earrings/occasion/party-wear" },
        " when you add a brighter stone. That versatility makes office earrings some of the best value in your jewellery box.",
      ],
      "Comfort matters when you are wearing earrings for a ten-hour day, so these are built light with secure backs and an anti-tarnish, skin-safe finish that holds up to constant use. They also make a thoughtful, easy gift for a colleague or a new graduate starting work. Keep them dry, store them in a pouch, and they will stay desk-to-dinner ready. For more on matching earrings to the moment, see our occasions guide.",
    ],
    internalLinks: [
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Huggie Earrings", href: "/earrings/style/huggies" },
      { label: "Pearl Earrings", href: "/earrings/finish/pearl" },
      { label: "Gold Tone", href: "/earrings/finish/gold-tone" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
      { label: "Earring Gifts", href: "/earrings/occasion/gift" },
    ],
    faqs: [
      { q: "What earrings are best for the office?", a: "Minimalist studs, small huggies and slim hoops are ideal for the office — polished but understated. Pearl and simple gold-tone designs read especially professional for formal workplaces." },
      { q: "Are large earrings okay for work?", a: "It depends on your workplace, but as a rule smaller, quieter earrings are safest for formal settings. Save bold statement pairs for parties and festive occasions." },
      { q: "Are office wear earrings comfortable for long days?", a: "Yes. They are lightweight with secure backs and a skin-safe, anti-tarnish finish, so they stay comfortable and look fresh through long, back-to-back workdays." },
      { q: "Can office earrings be worn after work too?", a: "Absolutely. Minimal office styles double as daily wear, and adding a brighter stone or a slightly larger hoop takes them into low-key evening looks." },
      { q: "Do office wear earrings make a good gift?", a: "Yes. A classic pair of gold-tone or pearl studs is a safe, elegant and affordable gift — perfect for a colleague, friend or a new graduate." },
      { q: "Are these earrings suitable for sensitive ears?", a: "Yes. They use skin-safe, hypoallergenic metal with smooth posts, which keeps sensitive ears comfortable even with daily, all-day wear." },
    ],
  },

  "party-wear": {
    tier: 1,
    metaTitle: "Party Wear Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop party wear earrings at Pearl Bloom — vibrant, light-catching statements for evenings out, light and anti-tarnish. Steal the show tonight.",
    primaryKeyword: "party wear earrings",
    secondaryKeywords: ["party wear earrings for women", "party earrings", "evening earrings", "statement party earrings"],
    h1: "Party Wear Earrings for Women",
    lede: "Vibrant, light-catching statements built for dazzling evenings out.",
    heroAlt: "Pearl Bloom sparkling party wear earrings catching the light on a cream background",
    assignedBlog: "earrings-for-every-occasion",
    intro: [
      "Party wear earrings exist to be noticed. When the lights are low and the evening is yours, these are the pieces that catch every glint and finish the look. Pearl Bloom party wear earrings turn up the sparkle and scale — yet stay light enough to dance in all night, thanks to balanced builds and secure fittings.",
      [
        "This is where you can be bold. Reach for dramatic ",
        { text: "statement earrings", href: "/earrings/style/statement" },
        ", glamorous ",
        { text: "drop", href: "/earrings/style/drop" },
        " designs or big, high-shine ",
        { text: "hoops", href: "/earrings/style/hoop" },
        ". For maximum dazzle, look to ",
        { text: "crystal", href: "/earrings/finish/crystal" },
        " and ",
        { text: "American Diamond", href: "/earrings/finish/american-diamond" },
        " stones that throw light across the room.",
      ],
      [
        "Party earrings are all about pairing. Let bold earrings lead with a simple neckline and minimal necklace, or echo your outfit's colour with matching stones. For traditional celebrations, the look crosses neatly into ",
        { text: "festive wear", href: "/earrings/occasion/festive-wear" },
        " with jhumkas and chandbalis.",
      ],
      "Because these are affordable fashion pieces, you can match your earrings to a specific outfit or theme without hesitation — and own a whole shelf of show-stoppers for the price of one fine pair. Every design uses skin-safe, hypoallergenic metal with an anti-tarnish finish, so they sparkle now and store well for the next event. Keep them dry and flat between parties to protect every stone. For help planning looks by event, see our occasions guide.",
    ],
    internalLinks: [
      { label: "Statement Earrings", href: "/earrings/style/statement" },
      { label: "Drop Earrings", href: "/earrings/style/drop" },
      { label: "Crystal Earrings", href: "/earrings/finish/crystal" },
      { label: "American Diamond", href: "/earrings/finish/american-diamond" },
      { label: "Festive Wear", href: "/earrings/occasion/festive-wear" },
      { label: "Hoop Earrings", href: "/earrings/style/hoop" },
    ],
    faqs: [
      { q: "What earrings should I wear to a party?", a: "Go bolder than daily wear — statement earrings, glamorous drops and large or sparkly hoops all work. Crystal and American Diamond stones add maximum light-catching dazzle for evenings." },
      { q: "Are party wear earrings heavy?", a: "Despite their size and sparkle, our party earrings are designed to stay lightweight with secure fittings, so they are comfortable enough to wear and dance in all night." },
      { q: "How do I style statement party earrings?", a: "Let them be the focus: keep your neckline simple and skip or minimise the necklace. Either match the stone colour to your outfit or let gold-tone and crystal act as a neutral." },
      { q: "Do the party earrings use real diamonds?", a: "No. They use crystal, cubic zirconia and American Diamond simulants for brilliant sparkle. They are affordable fashion jewellery designed to look luxe, not real diamonds." },
      { q: "Can I reuse party earrings for festivals?", a: "Yes. Many party styles cross over into festive wear, and traditional shapes like jhumkas and chandbalis work for both. It makes party earrings great value." },
      { q: "How do I store party earrings between events?", a: "Keep them dry and lay them flat in a box or pouch so stones stay secure. Put them on after perfume and skincare, and wipe gently after wear to keep them sparkling." },
    ],
  },

  "wedding-wear": {
    tier: 1,
    metaTitle: "Wedding Wear Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop wedding wear earrings at Pearl Bloom — show-stopping grandeur that stays feather-light, skin-safe and anti-tarnish. Shine through every ceremony.",
    primaryKeyword: "wedding wear earrings",
    secondaryKeywords: ["wedding earrings for women", "wedding guest earrings", "heavy earrings", "chandbali wedding earrings"],
    h1: "Wedding Wear Earrings for Women",
    lede: "Show-stopping grandeur crafted to stay feather-light through the longest celebrations.",
    heroAlt: "Pearl Bloom ornate gold-tone wedding wear earrings on a cream background",
    assignedBlog: "earrings-for-every-occasion",
    intro: [
      "Weddings call for earrings that can keep up with the occasion — rich, ornate and photogenic, but comfortable enough to last from the morning rituals to the final dance. Pearl Bloom wedding wear earrings give you that show-stopping grandeur in feather-light builds, so you look every bit the part without the all-day weight of traditional heavy pieces.",
      [
        "For the big day and the events around it, traditional shapes lead. Regal ",
        { text: "chandbali earrings", href: "/earrings/style/chandbali" },
        " and ornate ",
        { text: "jhumka", href: "/earrings/style/jhumka" },
        " designs are timeless against lehengas and saris, while ",
        { text: "kundan", href: "/earrings/finish/kundan" },
        " and ",
        { text: "American Diamond", href: "/earrings/finish/american-diamond" },
        " detailing brings the sparkle that photographs beautifully.",
      ],
      [
        "Whether you are the bride, bridesmaid or guest, there is a piece here for your role. Brides and close family can go all-out with our ",
        { text: "bridal", href: "/earrings/occasion/bridal" },
        " edit, while guests can pick lighter, elegant pairs that also work for ",
        { text: "festive wear", href: "/earrings/occasion/festive-wear" },
        " and future parties.",
      ],
      "Affordable pricing is a quiet superpower at wedding season: you can match earrings precisely to each outfit across multiple functions without overspending. Every pair uses skin-safe, hypoallergenic metal and an anti-tarnish finish, so they stay radiant across long ceremonies and store well afterwards. Keep them flat and dry between functions to protect the detailing. For a function-by-function plan, see our occasions guide.",
    ],
    internalLinks: [
      { label: "Chandbali Earrings", href: "/earrings/style/chandbali" },
      { label: "Jhumka Earrings", href: "/earrings/style/jhumka" },
      { label: "Kundan Earrings", href: "/earrings/finish/kundan" },
      { label: "American Diamond", href: "/earrings/finish/american-diamond" },
      { label: "Bridal", href: "/earrings/occasion/bridal" },
      { label: "Festive Wear", href: "/earrings/occasion/festive-wear" },
    ],
    faqs: [
      { q: "What earrings should I wear to a wedding?", a: "Choose ornate, traditional styles like chandbalis and jhumkas with kundan or American Diamond detailing. Brides can go bold and large; guests look elegant in lighter, sparkly pairs that suit the outfit." },
      { q: "Are heavy-looking wedding earrings comfortable?", a: "Ours are. Pearl Bloom wedding earrings are built in lightweight metal to look grand while staying comfortable, so they last through long ceremonies and celebrations." },
      { q: "Do wedding wear earrings contain real gold or diamonds?", a: "No. They are gold-tone fashion jewellery with simulant stones like American Diamond, CZ and kundan-style glass. They give a luxe bridal look at an affordable price and are not hallmarked." },
      { q: "Can guests and bridesmaids wear these too?", a: "Yes. There are pieces for every role — bold designs for brides and close family, and lighter, elegant pairs for guests and bridesmaids that also work for future festive occasions." },
      { q: "Will wedding earrings photograph well?", a: "Yes. The stone work and gold-tone finish are designed to catch light and look rich in photos, while staying light enough to wear comfortably throughout the shoot and the day." },
      { q: "How do I care for wedding earrings between functions?", a: "Store them flat and dry in a box, put them on after makeup and perfume, and wipe gently after each function. This protects the anti-tarnish finish and keeps stones secure." },
    ],
  },

  /* ===================== TIER 2 ===================== */
  "festive-wear": {
    tier: 2,
    metaTitle: "Festive Wear Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop festive wear earrings at Pearl Bloom — traditional jhumkas and chandbalis for every celebration, light and skin-safe. Festival-ready sparkle awaits.",
    primaryKeyword: "festive wear earrings",
    secondaryKeywords: ["festive earrings for women", "diwali earrings", "traditional earrings", "festive jhumka"],
    h1: "Festive Wear Earrings for Women",
    lede: "Traditional motifs and sparkle for every celebration on the calendar.",
    heroAlt: "Pearl Bloom festive gold-tone jhumka and chandbali earrings on a cream background",
    assignedBlog: "earrings-for-every-occasion",
    intro: [
      "Festival season calls for earrings with heritage and sparkle. Pearl Bloom festive wear earrings bring traditional bell-shaped motifs and crescent designs to every celebration — from Diwali and Navratri to Eid, Raksha Bandhan and family pujas — in a lightweight, skin-safe build that lasts through long days of festivities.",
      [
        "Reach for classic ",
        { text: "jhumka", href: "/earrings/style/jhumka" },
        " and regal ",
        { text: "chandbali", href: "/earrings/style/chandbali" },
        " shapes, or antique ",
        { text: "oxidised", href: "/earrings/finish/oxidised" },
        " pairs for a boho-ethnic mood. Festive looks cross over neatly into ",
        { text: "wedding wear", href: "/earrings/occasion/wedding-wear" },
        " and ",
        { text: "party wear", href: "/earrings/occasion/party-wear" },
        ", so each pair earns its place. Keep them dry and stored flat between celebrations to protect the detailing.",
      ],
    ],
    internalLinks: [
      { label: "Jhumka Earrings", href: "/earrings/style/jhumka" },
      { label: "Chandbali Earrings", href: "/earrings/style/chandbali" },
      { label: "Oxidised", href: "/earrings/finish/oxidised" },
      { label: "Wedding Wear", href: "/earrings/occasion/wedding-wear" },
      { label: "Party Wear", href: "/earrings/occasion/party-wear" },
    ],
    faqs: [
      { q: "What earrings are best for festivals?", a: "Traditional jhumkas and chandbalis are ideal for festive wear, with oxidised and kundan finishes adding ethnic character. They pair beautifully with saris, lehengas and kurtis." },
      { q: "Are festive earrings comfortable for all-day celebrations?", a: "Yes. Pearl Bloom festive earrings are built lightweight, so they keep the traditional look while staying comfortable through long days of celebration." },
      { q: "Can I reuse festive earrings for weddings and parties?", a: "Definitely. Festive styles cross over into wedding and party looks, so each pair offers great value across multiple occasions." },
      { q: "Are festive wear earrings skin-safe?", a: "Yes. They use skin-safe, hypoallergenic metal with an anti-tarnish finish, so they suit sensitive ears even during long festive days." },
    ],
  },

  bridal: {
    tier: 2,
    metaTitle: "Bridal Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop bridal earrings at Pearl Bloom — heirloom-style chandbalis and jhumkas for your big day, light and skin-safe. Photograph-ready, all-day comfort.",
    primaryKeyword: "bridal earrings",
    secondaryKeywords: ["bridal earrings for women", "bridal jhumka", "dulhan earrings", "wedding bridal earrings"],
    h1: "Bridal Earrings for Women",
    lede: "Heirloom-worthy statement pieces for the bride and her closest circle.",
    heroAlt: "Pearl Bloom ornate bridal chandbali earrings on a cream background",
    assignedBlog: "earrings-for-every-occasion",
    intro: [
      "Your wedding earrings should feel as special as the day itself. Pearl Bloom bridal earrings deliver heirloom-worthy grandeur — layered, intricate and luminous — while staying light enough to wear comfortably from the morning rituals to the last dance. They are designed to photograph beautifully and frame your face on the biggest day of all.",
      [
        "For bridal looks, ornate ",
        { text: "chandbali", href: "/earrings/style/chandbali" },
        " and ",
        { text: "kundan", href: "/earrings/finish/kundan" },
        " designs are timeless, while ",
        { text: "American Diamond", href: "/earrings/finish/american-diamond" },
        " detailing adds dazzling sparkle. Bridal naturally sits within our wider ",
        { text: "wedding wear", href: "/earrings/occasion/wedding-wear" },
        " edit, so there is something for every function and every member of the wedding party. Store them flat and dry to keep every stone secure.",
      ],
    ],
    internalLinks: [
      { label: "Chandbali Earrings", href: "/earrings/style/chandbali" },
      { label: "Kundan Earrings", href: "/earrings/finish/kundan" },
      { label: "American Diamond", href: "/earrings/finish/american-diamond" },
      { label: "Wedding Wear", href: "/earrings/occasion/wedding-wear" },
    ],
    faqs: [
      { q: "What are the best earrings for a bride?", a: "Ornate chandbalis and jhumkas, often with kundan or American Diamond detailing, are classic bridal choices. They look regal and photograph beautifully while staying comfortable." },
      { q: "Are bridal earrings heavy to wear all day?", a: "Pearl Bloom bridal earrings are built lightweight, so they keep the grand, traditional look while remaining comfortable through long wedding ceremonies and functions." },
      { q: "Do bridal earrings contain real gold or diamonds?", a: "No. They are gold-tone fashion jewellery with simulant stones like American Diamond and kundan-style glass. They give a luxe bridal look at an affordable price and are not hallmarked." },
      { q: "Will bridal earrings photograph well?", a: "Yes. The stone work and gold-tone finish are designed to catch light and look rich in photos, while staying light enough to wear comfortably all day." },
    ],
  },

  "college-wear": {
    tier: 2,
    metaTitle: "College Wear Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop college wear earrings at Pearl Bloom — trend-led, budget-friendly picks that go lecture-to-evening, light and anti-tarnish. Campus-ready every day.",
    primaryKeyword: "college wear earrings",
    secondaryKeywords: ["college earrings for women", "trendy earrings", "everyday college earrings", "affordable earrings"],
    h1: "College Wear Earrings for Women",
    lede: "Trend-forward, budget-friendly picks that move from lectures to evening plans.",
    heroAlt: "Pearl Bloom trendy, affordable college wear earrings on a cream background",
    assignedBlog: "earrings-for-every-occasion",
    intro: [
      "College style is all about expressing yourself without overspending — and your earrings are the easiest place to start. Pearl Bloom college wear earrings are trend-led, lightweight and genuinely affordable, so you can keep your look fresh, switch them up by mood, and never worry about a pair going out of style.",
      [
        "Mix and match freely: everyday ",
        { text: "studs", href: "/earrings/style/stud" },
        " and ",
        { text: "hoops", href: "/earrings/style/hoop" },
        ", boho ",
        { text: "oxidised", href: "/earrings/finish/oxidised" },
        " pieces and playful ",
        { text: "mismatch", href: "/earrings/style/mismatch" },
        " pairs all fit campus life. These styles move easily from lectures to evening plans, overlapping with ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        ". Anti-tarnish and skin-safe, they hold up to busy days and frequent wear.",
      ],
    ],
    internalLinks: [
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Hoop Earrings", href: "/earrings/style/hoop" },
      { label: "Oxidised", href: "/earrings/finish/oxidised" },
      { label: "Mismatch Earrings", href: "/earrings/style/mismatch" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
    ],
    faqs: [
      { q: "What earrings are best for college?", a: "Lightweight, trend-led studs, hoops, oxidised pieces and mismatched pairs are great for college — affordable, comfortable and easy to switch up from day to evening." },
      { q: "Are college wear earrings affordable?", a: "Yes. Pearl Bloom college wear earrings are budget-friendly fashion jewellery, so you can own several pairs and refresh your look as trends change." },
      { q: "Are these earrings durable for everyday campus use?", a: "Yes. They use an anti-tarnish finish and skin-safe metal, so they hold up to busy, everyday wear while staying comfortable." },
      { q: "Can college earrings be worn for evenings out?", a: "Absolutely. Many styles move easily from lectures to evening plans — just add a bolder hoop or a sparkly stud to dress up the look." },
    ],
  },

  gift: {
    tier: 2,
    metaTitle: "Earring Gifts for Women | Pearl Bloom",
    metaDescription:
      "Shop earring gifts at Pearl Bloom — pre-boxed, curated pairs to love, light, skin-safe and anti-tarnish. Thoughtful gifting without breaking the bank.",
    primaryKeyword: "earrings gift",
    secondaryKeywords: ["earring gifts for women", "gift earrings", "birthday gift earrings", "gift for her"],
    h1: "Earring Gifts for Women",
    lede: "Pre-boxed, thoughtfully curated picks to show you care.",
    heroAlt: "Pearl Bloom earring gift in a presentation box on a cream background",
    assignedBlog: "earrings-for-every-occasion",
    intro: [
      "Earrings are one of the easiest gifts to get right — personal, wearable and suited to almost anyone. Pearl Bloom earring gifts are thoughtfully curated and pre-boxed, so you can show you care without the stress of guessing. They make ideal presents for birthdays, anniversaries, Raksha Bandhan, festivals and just-because moments.",
      [
        "For a safe, elegant choice, classic ",
        { text: "stud", href: "/earrings/style/stud" },
        " and ",
        { text: "pearl", href: "/earrings/finish/pearl" },
        " designs suit every age and style, while a coordinated ",
        { text: "earring set", href: "/earrings/occasion/set" },
        " offers extra value. Gifting a colleague or new graduate? Our ",
        { text: "office wear", href: "/earrings/occasion/office-wear" },
        " edit is full of polished, professional picks. Every pair is skin-safe and anti-tarnish, so the gift keeps looking lovely.",
      ],
    ],
    internalLinks: [
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Pearl Earrings", href: "/earrings/finish/pearl" },
      { label: "Earrings Set", href: "/earrings/occasion/set" },
      { label: "Office Wear", href: "/earrings/occasion/office-wear" },
    ],
    faqs: [
      { q: "What earrings make a good gift?", a: "Classic gold-tone or pearl studs are a safe, elegant gift for almost anyone, while curated earring sets add extra value. They are personal, wearable and affordable." },
      { q: "Are the earrings gift-ready?", a: "Yes. Pearl Bloom earring gifts are thoughtfully curated and pre-boxed, so they are ready to give for birthdays, anniversaries, festivals and more." },
      { q: "Are these earrings safe for sensitive ears as a gift?", a: "Yes. They use skin-safe, hypoallergenic metal with an anti-tarnish finish, so they suit most people, including those with sensitive ears." },
      { q: "Are earring gifts affordable?", a: "Very. As fashion jewellery, they offer a premium look at value-for-money prices, so you can give something beautiful without overspending." },
    ],
  },

  set: {
    tier: 2,
    metaTitle: "Earrings Set for Women | Pearl Bloom",
    metaDescription:
      "Shop earrings sets at Pearl Bloom — curated combo and stacking packs at great value, light, skin-safe and anti-tarnish. Build your perfect ear stack.",
    primaryKeyword: "earrings set",
    secondaryKeywords: ["earring sets for women", "combo earrings", "multipack earrings", "stud set"],
    h1: "Earrings Sets for Women",
    lede: "Curated combo and stacking packs to build the perfect ear.",
    heroAlt: "Pearl Bloom curated earrings set with multiple coordinated pairs on a cream background",
    assignedBlog: "earrings-for-every-occasion",
    intro: [
      "Earrings sets make building a coordinated, multi-pierced look effortless — and far better value than buying pairs one at a time. Pearl Bloom earring sets bundle curated combos and stacking packs chosen by our stylists, so the pieces always work together and you get more ways to wear them for less.",
      [
        "Sets are perfect for stacking: combine ",
        { text: "studs", href: "/earrings/style/stud" },
        " and ",
        { text: "huggies", href: "/earrings/style/huggies" },
        " across multiple piercings, or mix a few finishes for variety. They are brilliant for ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        " rotations and make a generous, ready-to-give ",
        { text: "gift", href: "/earrings/occasion/gift" },
        ". Every piece is skin-safe and anti-tarnish, so the whole set keeps its shine.",
      ],
    ],
    internalLinks: [
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Huggie Earrings", href: "/earrings/style/huggies" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
      { label: "Earring Gifts", href: "/earrings/occasion/gift" },
    ],
    faqs: [
      { q: "What is included in an earrings set?", a: "Earring sets bundle multiple coordinated pairs — often a mix of studs, huggies and hoops — curated to work together for a multi-pierced or stacked look." },
      { q: "Are earring sets good value?", a: "Yes. Buying a curated set is more economical than buying pairs individually, and you get more ways to mix, match and stack your look." },
      { q: "Are earring sets good for stacking?", a: "Definitely. Sets are designed for layering across multiple piercings, making it easy to build a coordinated, curated ear." },
      { q: "Are earring sets skin-safe and anti-tarnish?", a: "Yes. Every piece in the set uses skin-safe, hypoallergenic metal with an anti-tarnish finish for lasting shine and comfortable wear." },
    ],
  },
};
