import type { CollectionSeoMap } from "./types";

/* ------------------------------------------------------------------
   STYLE facet SEO content. Keyed by slug (see libs/earringCategories.ts).
   Tier 1: stud, hoop, drop, statement, jhumka, chandbali.
   Tier 2: dangle, ear-cuffs, mismatch, clip-on, long, huggies, bali.
------------------------------------------------------------------- */

export const STYLE_SEO: CollectionSeoMap = {
  /* ===================== TIER 1 ===================== */
  stud: {
    tier: 1,
    metaTitle: "Stud Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop stud earrings for women at Pearl Bloom — lightweight, anti-tarnish and skin-safe gold-tone studs for daily wear. Find your everyday pair today.",
    primaryKeyword: "stud earrings",
    secondaryKeywords: ["stud earrings for women", "gold stud earrings", "small studs", "daily stud earrings"],
    h1: "Stud Earrings for Women",
    lede: "Lightweight, lobe-hugging studs for effortless everyday elegance.",
    heroAlt: "Pearl Bloom gold-tone stud earrings arranged on a warm cream surface",
    assignedBlog: "stud-earrings-everyday-style-guide",
    intro: [
      "Stud earrings are the quiet workhorses of any jewellery box — small, secure and endlessly wearable. At Pearl Bloom, our stud earrings for women sit flush against the lobe with featherlight balance, so you can wear them from your first coffee to the last message of the night and forget they are even there. Each pair is crafted in skin-safe, hypoallergenic metal with an anti-tarnish finish, which means no dull, faded shine after a few weeks and no irritation for sensitive ears.",
      [
        "Studs are the easiest earrings to style. A simple gold-tone dot or a sparkling ",
        { text: "CZ", href: "/earrings/finish/cz" },
        " solitaire is perfect for ",
        { text: "office wear", href: "/earrings/occasion/office-wear" },
        ", while ",
        { text: "pearl", href: "/earrings/finish/pearl" },
        " and floral studs feel soft and romantic for evenings. Because they are so understated, studs also make the perfect first layer in a stacked ear — pair them with ",
        { text: "hoops", href: "/earrings/style/hoop" },
        " or huggies higher up for a curated, multi-pierced look.",
      ],
      [
        "Comfort is the whole point of a stud, so we obsess over weight and post quality. Smooth, snag-free posts slide in easily and secure push-backs hold them in place through the busiest days. The result is a pair you can genuinely wear every single day — which is exactly why studs are our most popular pick for ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        ".",
      ],
      "Because these are affordable fashion earrings, you can build a small wardrobe of studs — classic gold-tone, bright crystal, calm pearl — for the price of a single fine-jewellery pair. To keep them looking new, store them dry, keep them away from perfume and lotion, and wipe with a soft cloth now and then; the anti-tarnish coating handles the rest.",
    ],
    internalLinks: [
      { label: "Hoop Earrings", href: "/earrings/style/hoop" },
      { label: "Huggie Earrings", href: "/earrings/style/huggies" },
      { label: "Pearl Earrings", href: "/earrings/finish/pearl" },
      { label: "CZ Earrings", href: "/earrings/finish/cz" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
      { label: "Office Wear", href: "/earrings/occasion/office-wear" },
    ],
    faqs: [
      { q: "Are stud earrings good for daily wear?", a: "Yes. Studs are lightweight, sit close to the lobe and use secure push-backs, so they are ideal for all-day, every-day wear. The anti-tarnish finish keeps them looking new even with frequent use." },
      { q: "Are Pearl Bloom studs suitable for sensitive ears?", a: "Yes. Our studs are made from skin-safe, hypoallergenic materials with smooth posts, which makes them comfortable for sensitive and newly healed ears." },
      { q: "Are the stones in the studs real diamonds?", a: "No. Sparkling studs use cubic zirconia (CZ), crystal or American Diamond simulants for brilliance. They give a diamond-bright look but are not real diamonds." },
      { q: "What kind of backs do the studs use?", a: "Most studs use friction (push-back) backs that are easy to put on and hold securely. They are simple to insert and comfortable to wear all day." },
      { q: "Can I wear stud earrings while sleeping or showering?", a: "Plain, lightweight studs can usually stay in. For stone-set or pearl studs, remove them before long showers or swimming and keep them dry to protect the shine." },
      { q: "How do I stop my studs from tarnishing?", a: "The anti-tarnish coating does most of the work. Store them dry, avoid contact with perfume, lotion and sweat where possible, and wipe gently with a soft cloth to keep them bright." },
    ],
  },

  hoop: {
    tier: 1,
    metaTitle: "Hoop Earrings for Women | Pearl Bloom",
    metaDescription:
      "Discover hoop earrings for women at Pearl Bloom — from thin everyday gold-tone hoops to bold loops, all anti-tarnish and skin-safe. Shop the edit now.",
    primaryKeyword: "hoop earrings",
    secondaryKeywords: ["hoop earrings for women", "gold hoops", "small hoops", "chunky hoops"],
    h1: "Hoop Earrings for Women",
    lede: "From whisper-thin everyday rings to bold statement loops — secure and feather-light.",
    heroAlt: "Pearl Bloom gold-tone hoop earrings in small and large sizes on a cream background",
    assignedBlog: "how-to-style-hoop-earrings-face-shape",
    intro: [
      "Few earrings are as versatile as the hoop. A thin gold-tone ring reads quiet and classic by day; a bold, chunky loop turns heads by night — and everything in between has a place in your rotation. Pearl Bloom hoop earrings for women are built around smooth, secure closures and a balanced weight, so even larger loops stay comfortable from morning commute to midnight.",
      [
        "Sizing is where hoops get fun. Petite ",
        { text: "huggie", href: "/earrings/style/huggies" },
        " hoops hug the lobe for a modern, stackable everyday staple, while mid-size hoops are the reliable all-rounder that suits almost every face shape. Want texture and tradition? Our ridged ",
        { text: "bali", href: "/earrings/style/bali" },
        " hoops bring an ethnic edge. For a layered ear, mix a hoop with a simple ",
        { text: "stud", href: "/earrings/style/stud" },
        " in a second piercing.",
      ],
      [
        "Hoops move effortlessly between occasions. Slim, lightweight rings are perfect for ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        " and the office, while larger, high-shine or stone-studded loops bring instant glamour to ",
        { text: "party wear", href: "/earrings/occasion/party-wear" },
        ". A warm ",
        { text: "gold-plated", href: "/earrings/finish/gold-plated" },
        " finish flatters every skin tone and pairs with both Indian and Western outfits.",
      ],
      "Every pair is finished with a skin-safe, anti-tarnish coating so the colour stays rich and the metal stays kind to sensitive ears — even with daily wear. Not sure which size flatters you most? Our guide to styling hoops by face shape takes the guesswork out, so you can buy the loop that looks made for you.",
    ],
    internalLinks: [
      { label: "Huggie Earrings", href: "/earrings/style/huggies" },
      { label: "Bali Earrings", href: "/earrings/style/bali" },
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Gold Plated", href: "/earrings/finish/gold-plated" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
      { label: "Party Wear", href: "/earrings/occasion/party-wear" },
    ],
    faqs: [
      { q: "Which hoop earring size should I choose?", a: "Small hoops and huggies suit daily and office wear and layer well; mid-size hoops are a versatile all-rounder; large hoops make a statement for parties. Pick by how much attention you want them to draw." },
      { q: "Are big hoop earrings heavy or uncomfortable?", a: "Our larger hoops are designed to stay lightweight with balanced weight distribution, so they remain comfortable for hours without dragging on the lobe." },
      { q: "Do the hoops have secure closures?", a: "Yes. Hoops use smooth hinged or click closures that snap shut securely and are easy to open, so they stay put through a busy day or night." },
      { q: "Are these hoops anti-tarnish and skin-safe?", a: "Yes. Every pair has an anti-tarnish coating over skin-safe, hypoallergenic metal, so the gold-tone colour lasts and the hoops suit sensitive ears." },
      { q: "Can I wear hoop earrings every day?", a: "Absolutely. Thin and mid-size hoops are made for daily wear — light, secure and easy to pair with any outfit. Keep them dry and wipe them occasionally to maintain shine." },
      { q: "Will hoops suit my face shape?", a: "There is a hoop for every face shape. As a rule, rounded faces are flattered by larger or angular hoops and longer faces by smaller ones — our hoop styling guide explains it in detail." },
    ],
  },

  drop: {
    tier: 1,
    metaTitle: "Drop Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop drop earrings for women at Pearl Bloom — graceful gold-tone drops that catch the light, lightweight and anti-tarnish. Find your perfect fall today.",
    primaryKeyword: "drop earrings",
    secondaryKeywords: ["drop earrings for women", "gold drop earrings", "tear drop earrings", "party drop earrings"],
    h1: "Drop Earrings for Women",
    lede: "A single elegant fall of gold and stone that catches the light with every turn.",
    heroAlt: "Pearl Bloom gold-tone drop earrings with stones, photographed on a cream background",
    assignedBlog: "types-of-earrings-guide",
    intro: [
      "Drop earrings add movement and grace without the drama of a full chandelier. A single, elegant element falls just below the lobe and sways gently as you move, catching the light with every turn of the head. Pearl Bloom drop earrings for women are weighted to swing softly — never to drag — so they feel as good as they look across a long evening.",
      [
        "Drops are wonderfully flattering: the vertical line lengthens the neck and frames the face. Keep it subtle with a small ",
        { text: "stone", href: "/earrings/finish/stone" },
        " or ",
        { text: "crystal", href: "/earrings/finish/crystal" },
        " drop for the office, or scale up to a longer fall for occasions. If you love extra motion, explore our layered ",
        { text: "dangle earrings", href: "/earrings/style/dangle" },
        ", and for serious drama see the elongating ",
        { text: "long earrings", href: "/earrings/style/long" },
        " edit.",
      ],
      [
        "These are the earrings you reach for when an outfit needs a little polish. A pair of gold-tone drops with a single bright stone elevates ",
        { text: "party wear", href: "/earrings/occasion/party-wear" },
        " in seconds, while pearl and soft-toned drops bring understated elegance to ",
        { text: "wedding wear", href: "/earrings/occasion/wedding-wear" },
        " and guest looks.",
      ],
      "As with everything at Pearl Bloom, the finish is anti-tarnish and the metal is skin-safe and hypoallergenic, so your drops keep their glow and stay comfortable for hours. Wipe them gently after wear and store them flat to keep stones secure and shine intact — small habits that keep affordable fashion earrings looking premium far longer.",
    ],
    internalLinks: [
      { label: "Dangle Earrings", href: "/earrings/style/dangle" },
      { label: "Long Earrings", href: "/earrings/style/long" },
      { label: "Stone Earrings", href: "/earrings/finish/stone" },
      { label: "Crystal Earrings", href: "/earrings/finish/crystal" },
      { label: "Party Wear", href: "/earrings/occasion/party-wear" },
      { label: "Wedding Wear", href: "/earrings/occasion/wedding-wear" },
    ],
    faqs: [
      { q: "What is the difference between drop and dangle earrings?", a: "A drop earring has a single element that hangs just below the lobe and stays fairly still, while a dangle earring has elements that move and swing more freely. Drops read a little more refined; dangles add more motion." },
      { q: "Are drop earrings heavy?", a: "No. Pearl Bloom drops are designed to be lightweight and balanced, so they swing gently without pulling on the lobe, even over a long evening." },
      { q: "Are drop earrings suitable for the office?", a: "Yes — a small, simple stone or pearl drop is elegant and understated enough for work, while longer, sparklier drops are better suited to parties and occasions." },
      { q: "Are the stones real gemstones?", a: "No. Our drops use crystals, coloured stones and simulants for colour and sparkle. They are fashion jewellery designed to look luxe at an affordable price, not real precious gemstones." },
      { q: "Do drop earrings suit every face shape?", a: "Generally yes. The vertical line of a drop lengthens and flatters most faces; rounder faces especially benefit from a longer drop, while shorter drops keep things balanced on longer faces." },
      { q: "How do I care for my drop earrings?", a: "Keep them dry, avoid perfume and lotion on the metal, wipe gently with a soft cloth and store them flat. This protects the anti-tarnish finish and keeps set stones secure." },
    ],
  },

  statement: {
    tier: 1,
    metaTitle: "Statement Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop statement earrings for women at Pearl Bloom — bold, head-turning designs that stay light and anti-tarnish. Make every outfit's final word count.",
    primaryKeyword: "statement earrings",
    secondaryKeywords: ["statement earrings for women", "big earrings", "bold earrings", "party statement earrings"],
    h1: "Statement Earrings for Women",
    lede: "Bold, architectural pieces that finish the outfit — big on presence, light on the lobe.",
    heroAlt: "Pearl Bloom bold gold-tone statement earrings displayed on a cream background",
    assignedBlog: "types-of-earrings-guide",
    intro: [
      "Some outfits need a final word, and that is exactly what statement earrings are for. Bold, architectural and impossible to ignore, these are the pieces you reach for when you want one accessory to do all the talking. Pearl Bloom statement earrings for women are crafted big on presence but gentle on weight, so you get maximum impact without the all-evening ache.",
      [
        "A great statement pair lets you keep the rest of your look simple — a plain outfit plus dramatic earrings is the easiest way to feel dressed up. For festive and ethnic occasions, our ",
        { text: "chandbali earrings", href: "/earrings/style/chandbali" },
        " and ",
        { text: "long earrings", href: "/earrings/style/long" },
        " deliver real grandeur, while sculptural ",
        { text: "dangle", href: "/earrings/style/dangle" },
        " designs bring modern, eye-catching movement.",
      ],
      [
        "Statement earrings are made for moments. They are the natural choice for ",
        { text: "party wear", href: "/earrings/occasion/party-wear" },
        " and ",
        { text: "festive wear", href: "/earrings/occasion/festive-wear" },
        ", where a little extra sparkle and scale is welcome. Choose high-shine gold-tone for glamour, or coloured stones to tie back to your outfit.",
      ],
      "Because they are designed as affordable fashion jewellery, you can own several show-stoppers and rotate them by mood and season — without a fine-jewellery budget. Each pair uses skin-safe, hypoallergenic metal and an anti-tarnish finish, and secure fittings keep larger designs sitting right all night. Store them flat, keep them dry, and they will be ready for your next entrance.",
    ],
    internalLinks: [
      { label: "Chandbali Earrings", href: "/earrings/style/chandbali" },
      { label: "Long Earrings", href: "/earrings/style/long" },
      { label: "Dangle Earrings", href: "/earrings/style/dangle" },
      { label: "Party Wear", href: "/earrings/occasion/party-wear" },
      { label: "Festive Wear", href: "/earrings/occasion/festive-wear" },
      { label: "Wedding Wear", href: "/earrings/occasion/wedding-wear" },
    ],
    faqs: [
      { q: "Are statement earrings heavy to wear?", a: "Not at Pearl Bloom. Our statement designs are engineered to stay lightweight despite their size, with balanced weight and secure fittings so they stay comfortable through an event." },
      { q: "How do I style statement earrings?", a: "Let them lead. Keep the rest of your look simple — minimal necklace, clean neckline — so the earrings stand out. They pair best with parties, festivals and special occasions." },
      { q: "Are statement earrings good for sensitive ears?", a: "Yes. They use skin-safe, hypoallergenic metal, and the lightweight build means less pull on the lobe, which helps comfort for sensitive ears." },
      { q: "Do statement earrings work for festive and ethnic outfits?", a: "Definitely. Chandbali, long and ornate gold-tone statement styles are ideal for festive and traditional wear, while sculptural modern designs suit Western party looks." },
      { q: "Are these earrings anti-tarnish?", a: "Yes. Every statement pair has an anti-tarnish finish, so the colour stays rich between occasions. Store them dry and flat to keep stones and shine intact." },
    ],
  },

  jhumka: {
    tier: 1,
    metaTitle: "Jhumka Earrings Online | Pearl Bloom",
    metaDescription:
      "Shop jhumka earrings online at Pearl Bloom — classic bell-domed jhumkas in lightweight, anti-tarnish gold-tone for festive and daily wear. Buy now.",
    primaryKeyword: "jhumka earrings",
    secondaryKeywords: ["jhumkas online", "gold jhumka earrings", "oxidised jhumka", "festive jhumka earrings"],
    h1: "Jhumka Earrings for Women",
    lede: "The timeless bell-domed silhouette, reimagined in lightweight, anti-tarnish gold-tone.",
    heroAlt: "Pearl Bloom gold-tone jhumka earrings with fringe detailing on a cream background",
    assignedBlog: "how-to-style-jhumkas-and-chandbalis",
    intro: [
      "The jhumka is one of India's most loved earring shapes, and for good reason. Its bell-domed silhouette and delicate fringe chime softly with movement, carrying generations of tradition in a single, graceful form. Pearl Bloom jhumka earrings keep that heritage shape but build it in lightweight, anti-tarnish gold-tone metal — so you get the classic look with modern, all-day comfort.",
      [
        "Jhumkas are far more versatile than people expect. A small gold-tone jhumka is lovely enough for ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        " with a kurti, while larger, embellished pairs are made for ",
        { text: "festive wear", href: "/earrings/occasion/festive-wear" },
        " and ",
        { text: "wedding", href: "/earrings/occasion/wedding-wear" },
        " celebrations. For an antique, artisanal mood, our ",
        { text: "oxidised", href: "/earrings/finish/oxidised" },
        " jhumkas pair beautifully with both ethnic and indo-western outfits.",
      ],
      [
        "If you love traditional silhouettes, explore the rest of the family too: regal ",
        { text: "chandbali earrings", href: "/earrings/style/chandbali" },
        " for crescent grandeur and glass-set ",
        { text: "kundan", href: "/earrings/finish/kundan" },
        " jhumkas for festive richness. Mix and match by occasion to build a small but complete ethnic earring wardrobe.",
      ],
      "Traditional does not have to mean heavy or high-maintenance. Our jhumkas use skin-safe, hypoallergenic metal and an anti-tarnish coating, so they stay bright through festival season and kind to sensitive ears through a long day of celebrations. Want help pairing them with saris, lehengas or even jeans? Our jhumka and chandbali styling guide has you covered.",
    ],
    internalLinks: [
      { label: "Chandbali Earrings", href: "/earrings/style/chandbali" },
      { label: "Oxidised Earrings", href: "/earrings/finish/oxidised" },
      { label: "Kundan Earrings", href: "/earrings/finish/kundan" },
      { label: "Festive Wear", href: "/earrings/occasion/festive-wear" },
      { label: "Wedding Wear", href: "/earrings/occasion/wedding-wear" },
      { label: "Bridal", href: "/earrings/occasion/bridal" },
    ],
    faqs: [
      { q: "Are jhumka earrings heavy?", a: "Traditional jhumkas can be heavy, but Pearl Bloom jhumkas are built in lightweight gold-tone metal so they keep the classic look while staying comfortable for long festive days." },
      { q: "Can I wear jhumkas for daily wear?", a: "Yes. Smaller, simpler jhumkas are perfect for everyday wear with kurtis and casual outfits, while larger embellished pairs suit festivals and weddings." },
      { q: "Are oxidised jhumkas different from gold-tone jhumkas?", a: "Yes. Oxidised jhumkas have a darkened, antique silver-tone finish for a boho, artisanal look, while gold-tone jhumkas give a bright, traditional gold appearance. Both are anti-tarnish." },
      { q: "Do these jhumkas suit sensitive ears?", a: "Yes. They are made from skin-safe, hypoallergenic metal with an anti-tarnish coating, which makes them comfortable for sensitive ears even during long celebrations." },
      { q: "What outfits go with jhumka earrings?", a: "Jhumkas pair beautifully with saris, lehengas, kurtis and salwar suits, and look striking with indo-western and fusion outfits too. They are a true all-occasion ethnic staple." },
      { q: "How do I care for my jhumkas after the festive season?", a: "Wipe them gently, keep them dry and away from perfume, and store them in a pouch or box. The anti-tarnish finish helps them stay bright until the next occasion." },
    ],
  },

  chandbali: {
    tier: 1,
    metaTitle: "Chandbali Earrings Online | Pearl Bloom",
    metaDescription:
      "Shop chandbali earrings at Pearl Bloom — regal crescent designs for festive and bridal looks, lightweight and skin-safe. Find your statement pair today.",
    primaryKeyword: "chandbali earrings",
    secondaryKeywords: ["chandbali earrings online", "bridal chandbali", "gold chandbali", "festive chandbali earrings"],
    h1: "Chandbali Earrings for Women",
    lede: "Crescent-moon grandeur layered in intricate detail for festive and bridal moments.",
    heroAlt: "Pearl Bloom gold-tone chandbali earrings with crescent detailing on a cream background",
    assignedBlog: "how-to-style-jhumkas-and-chandbalis",
    intro: [
      "Named for the crescent moon, the chandbali is the earring you wear when the occasion calls for old-world opulence. Layered, intricate and unmistakably regal, it has crowned brides and festival looks for generations. Pearl Bloom chandbali earrings capture that grandeur in lightweight, skin-safe metal, so you get the heirloom look without the heirloom weight.",
      [
        "Chandbalis are made for the biggest moments. They are a natural choice for ",
        { text: "bridal", href: "/earrings/occasion/bridal" },
        " and ",
        { text: "wedding wear", href: "/earrings/occasion/wedding-wear" },
        ", and they bring instant richness to ",
        { text: "festive wear", href: "/earrings/occasion/festive-wear" },
        " through the celebration season. For a coordinated ethnic look, pair them with the bell-domed ",
        { text: "jhumka", href: "/earrings/style/jhumka" },
        " family or glass-set ",
        { text: "kundan", href: "/earrings/finish/kundan" },
        " designs.",
      ],
      [
        "The detailing is what makes a chandbali special — fine layering, hanging pearls and stone work that catches the light. For maximum sparkle, look for ",
        { text: "American Diamond", href: "/earrings/finish/american-diamond" },
        " accents; for softer romance, pearl-dropped designs are timeless against bridal reds and pastels alike.",
      ],
      "Despite their scale, our chandbalis are engineered to photograph beautifully and wear comfortably, with an anti-tarnish finish that holds up across long ceremonies. They are affordable enough to match to specific outfits, yet detailed enough to look far more expensive than they are. Store them flat and dry between occasions to keep every stone and pearl secure.",
    ],
    internalLinks: [
      { label: "Jhumka Earrings", href: "/earrings/style/jhumka" },
      { label: "Kundan Earrings", href: "/earrings/finish/kundan" },
      { label: "American Diamond", href: "/earrings/finish/american-diamond" },
      { label: "Bridal", href: "/earrings/occasion/bridal" },
      { label: "Wedding Wear", href: "/earrings/occasion/wedding-wear" },
      { label: "Festive Wear", href: "/earrings/occasion/festive-wear" },
    ],
    faqs: [
      { q: "What are chandbali earrings?", a: "Chandbali earrings are a traditional Indian style shaped like a crescent moon (chand), built in layered, intricate detail. They are popular for bridal, wedding and festive looks." },
      { q: "Are chandbali earrings good for brides?", a: "Yes. Their regal, layered grandeur makes chandbalis a classic bridal choice. Pearl Bloom chandbalis stay lightweight and comfortable, so they wear well across long wedding ceremonies." },
      { q: "Are these chandbalis heavy?", a: "No. They are designed in lightweight, skin-safe metal to give the look of a heavy traditional piece while staying comfortable to wear and easy to photograph." },
      { q: "Do the chandbalis have real diamonds or pearls?", a: "No. They use American Diamond and CZ simulants and faux or shell pearls for sparkle and softness. They are affordable fashion jewellery, not real precious stones." },
      { q: "What should I wear chandbali earrings with?", a: "Chandbalis shine with saris, lehengas and anarkalis, and look striking with indo-western gowns. Pair with minimal neckwear so the earrings stay the focal point." },
      { q: "Are chandbali earrings anti-tarnish?", a: "Yes. The anti-tarnish finish keeps the gold-tone bright between occasions. Keep them dry, away from perfume, and stored flat to protect the detailing." },
    ],
  },

  /* ===================== TIER 2 ===================== */
  dangle: {
    tier: 2,
    metaTitle: "Dangle Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop dangle earrings for women at Pearl Bloom — shimmering gold-tone movement that's light on the lobe and anti-tarnish. Add a little sway to any look.",
    primaryKeyword: "dangle earrings",
    secondaryKeywords: ["dangle earrings for women", "long dangle earrings", "gold dangle earrings"],
    h1: "Dangle Earrings for Women",
    lede: "Layered elements that move and shimmer with every step.",
    heroAlt: "Pearl Bloom gold-tone dangle earrings with moving elements on a cream background",
    assignedBlog: "types-of-earrings-guide",
    intro: [
      "Dangle earrings are all about movement. Where a stud sits still, a dangle is built to sway — layered elements that catch the light and shimmer with every step, drawing the eye in a slow, deliberate cascade. Pearl Bloom dangle earrings deliver that motion while staying surprisingly light, so even longer designs never weigh down the lobe.",
      [
        "They sit naturally between a subtle ",
        { text: "drop", href: "/earrings/style/drop" },
        " and a full ",
        { text: "statement", href: "/earrings/style/statement" },
        " piece, which makes them wonderfully versatile. Choose a short, fluid dangle for everyday flair, or a longer, more elaborate pair for ",
        { text: "party wear", href: "/earrings/occasion/party-wear" },
        " and evenings out. For real length, see our ",
        { text: "long earrings", href: "/earrings/style/long" },
        " edit.",
      ],
      "As with every Pearl Bloom design, the finish is anti-tarnish and the metal is skin-safe and hypoallergenic, so your dangles keep their shine and stay comfortable through a long day or night. Store them flat and dry to keep moving parts and stones secure.",
    ],
    internalLinks: [
      { label: "Drop Earrings", href: "/earrings/style/drop" },
      { label: "Long Earrings", href: "/earrings/style/long" },
      { label: "Statement Earrings", href: "/earrings/style/statement" },
      { label: "Party Wear", href: "/earrings/occasion/party-wear" },
    ],
    faqs: [
      { q: "What is the difference between dangle and drop earrings?", a: "A drop earring hangs fairly still below the lobe, while a dangle earring has elements that move and swing more freely. Dangles add more visible motion." },
      { q: "Are dangle earrings heavy?", a: "No. Pearl Bloom dangles are designed to stay lightweight and balanced, so they sway gently without pulling on the lobe, even in longer designs." },
      { q: "Can I wear dangle earrings every day?", a: "Yes — shorter, simpler dangles are great for everyday wear, while longer, more elaborate pairs are better suited to parties and special occasions." },
      { q: "Are these dangle earrings anti-tarnish and skin-safe?", a: "Yes. Every pair uses an anti-tarnish finish over skin-safe, hypoallergenic metal, so they stay bright and comfortable for sensitive ears." },
    ],
  },

  "ear-cuffs": {
    tier: 2,
    metaTitle: "Ear Cuffs for Women | Pearl Bloom",
    metaDescription:
      "Shop ear cuffs for women at Pearl Bloom — no-piercing sculptural cuffs in skin-safe, anti-tarnish gold-tone. Get the editorial ear look in seconds.",
    primaryKeyword: "ear cuffs",
    secondaryKeywords: ["ear cuff earrings", "no piercing earrings", "gold ear cuffs", "ear cuffs for women"],
    h1: "Ear Cuff Earrings for Women",
    lede: "No-piercing sculptural metal that hugs the ear's edge.",
    heroAlt: "Pearl Bloom gold-tone ear cuffs that need no piercing, on a cream background",
    assignedBlog: "types-of-earrings-guide",
    intro: [
      "Ear cuffs are the easiest way to get an editorial, stacked-ear look without a single new piercing. These sculptural pieces hug the outer edge of the ear, held in place by a gentle, adjustable curve rather than a post — so anyone can wear them, pierced or not. Pearl Bloom ear cuffs are shaped to sit comfortably for hours in skin-safe, anti-tarnish metal.",
      [
        "They are brilliant for building a curated ear: wear one alone for a subtle accent, or layer a cuff above your usual ",
        { text: "studs", href: "/earrings/style/stud" },
        " and ",
        { text: "huggies", href: "/earrings/style/huggies" },
        " for a modern, multi-piece effect. If you love the no-piercing idea, our ",
        { text: "clip-on", href: "/earrings/style/clip-on" },
        " earrings offer the same freedom for the lobe.",
      ],
      [
        "Light, secure and endlessly restylable, ear cuffs are perfect for ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        " and a fuss-free way to experiment with trends. Adjust the curve gently to fit, store them dry, and they will keep their shape and shine.",
      ],
    ],
    internalLinks: [
      { label: "Clip-On Earrings", href: "/earrings/style/clip-on" },
      { label: "Huggie Earrings", href: "/earrings/style/huggies" },
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
    ],
    faqs: [
      { q: "Do ear cuffs need a piercing?", a: "No. Ear cuffs clip onto the outer edge of the ear with an adjustable curve, so they need no piercing and can be worn by anyone." },
      { q: "Do ear cuffs stay on securely?", a: "Yes. The gentle, adjustable curve grips the ear's edge to hold the cuff in place comfortably. You can adjust it slightly for a more secure or relaxed fit." },
      { q: "Can I wear ear cuffs with studs?", a: "Absolutely. Ear cuffs are made for layering — pair one with studs and huggies in your existing piercings for a curated, stacked-ear look." },
      { q: "Are ear cuffs anti-tarnish and skin-safe?", a: "Yes. They use skin-safe, hypoallergenic metal with an anti-tarnish finish, so they stay bright and gentle on the ear." },
    ],
  },

  mismatch: {
    tier: 2,
    metaTitle: "Mismatch Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop mismatch earrings for women at Pearl Bloom — curated asymmetric pairs in lightweight, anti-tarnish gold-tone. Break the rules beautifully today.",
    primaryKeyword: "mismatch earrings",
    secondaryKeywords: ["mismatched earrings", "asymmetric earrings", "trendy earrings for women"],
    h1: "Mismatch Earrings for Women",
    lede: "Two deliberately different earrings, curated to be worn together.",
    heroAlt: "Pearl Bloom mismatched asymmetric earrings shown as a coordinated pair on a cream background",
    assignedBlog: "types-of-earrings-guide",
    intro: [
      "Mismatched earrings turn asymmetry into a style statement. Instead of an identical pair, you wear two deliberately different-but-coordinated designs together — a look that feels playful, modern and effortlessly creative. At Pearl Bloom, our mismatch earrings are curated so the two sides always belong together, taking the guesswork out of the trend.",
      [
        "They are a quick way to make a simple outfit feel considered, and they pair beautifully with a layered, multi-pierced ear. Build on them with a classic ",
        { text: "stud", href: "/earrings/style/stud" },
        " or scale up the drama with ",
        { text: "statement", href: "/earrings/style/statement" },
        " designs. The look is especially popular for ",
        { text: "college wear", href: "/earrings/occasion/college-wear" },
        " and relaxed ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        ", where personality matters more than symmetry.",
      ],
      "Every pair uses skin-safe, hypoallergenic metal with an anti-tarnish finish, so they stay bright and comfortable. Store them together so you never lose a side, and wipe gently to keep both halves shining.",
    ],
    internalLinks: [
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Statement Earrings", href: "/earrings/style/statement" },
      { label: "College Wear", href: "/earrings/occasion/college-wear" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
    ],
    faqs: [
      { q: "What are mismatched earrings?", a: "Mismatched earrings are two deliberately different but coordinated designs worn together, creating a playful, asymmetric look. Pearl Bloom curates the pairs so they always belong together." },
      { q: "Are mismatch earrings meant to be worn together?", a: "Yes. Although the two sides differ, they are designed as a set to be worn as a pair for an intentional, stylish asymmetry." },
      { q: "When should I wear mismatched earrings?", a: "They are great for casual, college and daily looks, and any time you want to add a modern, creative twist to a simple outfit." },
      { q: "Are these earrings anti-tarnish and skin-safe?", a: "Yes. They use skin-safe, hypoallergenic metal with an anti-tarnish finish for lasting shine and comfortable wear." },
    ],
  },

  "clip-on": {
    tier: 2,
    metaTitle: "Clip-On Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop clip-on earrings for women at Pearl Bloom — comfy, cushioned clips for non-pierced ears in anti-tarnish gold-tone. All the drama, no piercing.",
    primaryKeyword: "clip on earrings",
    secondaryKeywords: ["clip-on earrings for women", "non pierced earrings", "clip earrings"],
    h1: "Clip-On Earrings for Women",
    lede: "Cushioned, comfortable clips for non-pierced and sensitive ears.",
    heroAlt: "Pearl Bloom clip-on earrings with cushioned backs for non-pierced ears on a cream background",
    assignedBlog: "types-of-earrings-guide",
    intro: [
      "Clip-on earrings prove you do not need pierced ears to enjoy great jewellery. A cushioned clip mechanism grips the lobe gently but securely, giving you all the style with none of the piercing — ideal for un-pierced ears, sensitive ears, or anyone who simply prefers not to commit. Pearl Bloom clip-ons are designed to hold comfortably without pinching.",
      [
        "From simple everyday designs to dressier drops, clip-ons cover the same ground as pierced styles. If you like the no-piercing approach, pair them with our ",
        { text: "ear cuffs", href: "/earrings/style/ear-cuffs" },
        " for a full look, or keep it classic with clip-on versions of the ",
        { text: "stud", href: "/earrings/style/stud" },
        ". They also make a thoughtful ",
        { text: "gift", href: "/earrings/occasion/gift" },
        " for someone without piercings.",
      ],
      [
        "Light and skin-safe with an anti-tarnish finish, they are easy for ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        ". Adjust the clip gently for the most comfortable fit, and store them dry to protect the cushion and shine.",
      ],
    ],
    internalLinks: [
      { label: "Ear Cuffs", href: "/earrings/style/ear-cuffs" },
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Earring Gifts", href: "/earrings/occasion/gift" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
    ],
    faqs: [
      { q: "Do clip-on earrings hurt?", a: "They should not. Pearl Bloom clip-ons use cushioned clips that grip gently. You can adjust the clip slightly for a comfortable fit and take short breaks during very long wear." },
      { q: "Do clip-on earrings stay on securely?", a: "Yes. The clip mechanism holds the earring firmly to the lobe, so it stays in place through normal wear while remaining easy to put on and take off." },
      { q: "Who are clip-on earrings for?", a: "They are ideal for anyone with un-pierced or sensitive ears, or anyone who prefers not to commit to piercings but still wants stylish earrings." },
      { q: "Are clip-on earrings anti-tarnish and skin-safe?", a: "Yes. They use skin-safe, hypoallergenic metal with an anti-tarnish finish for lasting shine and gentle, comfortable wear." },
    ],
  },

  long: {
    tier: 2,
    metaTitle: "Long Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop long earrings for women at Pearl Bloom — elongating gold-tone drops that stay feather-light and anti-tarnish. Find your neck-lengthening pair now.",
    primaryKeyword: "long earrings",
    secondaryKeywords: ["long earrings for women", "long dangle earrings", "party long earrings"],
    h1: "Long Earrings for Women",
    lede: "Elongating, neck-lengthening drops that fall well past the lobe.",
    heroAlt: "Pearl Bloom long gold-tone earrings that fall past the lobe on a cream background",
    assignedBlog: "types-of-earrings-guide",
    intro: [
      "Long earrings are pure drama in the most flattering way. Falling well past the lobe, they draw a vertical line that lengthens the neck and elongates the whole silhouette — an instant dose of elegance. Pearl Bloom long earrings keep that statement length feather-light, so they sway beautifully without dragging.",
      [
        "They are close cousins of ",
        { text: "drop", href: "/earrings/style/drop" },
        " and ",
        { text: "dangle", href: "/earrings/style/dangle" },
        " styles, simply taken further, and they shade naturally into ",
        { text: "statement", href: "/earrings/style/statement" },
        " territory. Long earrings shine at ",
        { text: "party wear", href: "/earrings/occasion/party-wear" },
        " and ",
        { text: "wedding", href: "/earrings/occasion/wedding-wear" },
        " events, where their movement and length catch the light across a room. Keep your neckline simple to let them lead.",
      ],
      "Each pair uses skin-safe, hypoallergenic metal and an anti-tarnish finish, with balanced weight for all-evening comfort. Store them flat and dry so the longest designs keep every link and stone secure.",
    ],
    internalLinks: [
      { label: "Drop Earrings", href: "/earrings/style/drop" },
      { label: "Dangle Earrings", href: "/earrings/style/dangle" },
      { label: "Statement Earrings", href: "/earrings/style/statement" },
      { label: "Party Wear", href: "/earrings/occasion/party-wear" },
      { label: "Wedding Wear", href: "/earrings/occasion/wedding-wear" },
    ],
    faqs: [
      { q: "Are long earrings comfortable to wear?", a: "Yes. Despite their length, Pearl Bloom long earrings are designed to be lightweight and balanced, so they stay comfortable through a long evening." },
      { q: "Do long earrings suit every face shape?", a: "Long earrings are especially flattering on rounder faces because they add length, and they look elegant on most face shapes. They pair beautifully with updos." },
      { q: "When should I wear long earrings?", a: "They are perfect for parties, weddings and special occasions where their movement and length can stand out. Keep the rest of your jewellery minimal." },
      { q: "Are long earrings anti-tarnish and skin-safe?", a: "Yes. Every pair uses an anti-tarnish finish over skin-safe, hypoallergenic metal for lasting shine and comfortable wear." },
    ],
  },

  huggies: {
    tier: 2,
    metaTitle: "Huggie Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop huggie earrings for women at Pearl Bloom — snug, stackable mini hoops in skin-safe, anti-tarnish gold-tone. Your new everyday staple awaits.",
    primaryKeyword: "huggie earrings",
    secondaryKeywords: ["huggie hoops", "small hoop earrings", "gold huggies", "everyday huggies"],
    h1: "Huggie Earrings for Women",
    lede: "Petite hoops that hug the lobe close — snug, secure and stackable.",
    heroAlt: "Pearl Bloom small gold-tone huggie hoop earrings on a cream background",
    assignedBlog: "how-to-style-hoop-earrings-face-shape",
    intro: [
      "Huggie earrings are the petite hoops that 'hug' the lobe closely — small, snug and endlessly wearable. Their compact size and smooth click closure make them one of the most comfortable everyday earrings you can own, and the easiest to stack. Pearl Bloom huggies are sized to sit flush and secure, in a skin-safe, anti-tarnish finish.",
      [
        "They are a modern staple for a reason. Wear a single pair for understated ",
        { text: "daily wear", href: "/earrings/occasion/daily-wear" },
        " and ",
        { text: "office", href: "/earrings/occasion/office-wear" },
        " polish, or collect a few to build a layered, multi-pierced ear alongside ",
        { text: "studs", href: "/earrings/style/stud" },
        ". For larger loops and sizing tips, see the full ",
        { text: "hoop", href: "/earrings/style/hoop" },
        " range.",
      ],
      "Light, secure and easy to wear from morning to night, huggies keep their shine with simple care: store them dry and wipe gently. A small but mighty addition to any earring wardrobe.",
    ],
    internalLinks: [
      { label: "Hoop Earrings", href: "/earrings/style/hoop" },
      { label: "Stud Earrings", href: "/earrings/style/stud" },
      { label: "Daily Wear", href: "/earrings/occasion/daily-wear" },
      { label: "Office Wear", href: "/earrings/occasion/office-wear" },
    ],
    faqs: [
      { q: "What are huggie earrings?", a: "Huggie earrings are very small hoops that sit snugly against the lobe, 'hugging' it closely. They are comfortable, secure and ideal for everyday wear and stacking." },
      { q: "Are huggies good for stacking?", a: "Yes. Their small size makes huggies perfect for building a layered, multi-pierced ear alongside studs and larger hoops." },
      { q: "Are huggie earrings comfortable for daily wear?", a: "Very. Their snug fit, light weight and secure click closure make them one of the most comfortable earrings for all-day, every-day wear." },
      { q: "Are huggie earrings anti-tarnish and skin-safe?", a: "Yes. They use skin-safe, hypoallergenic metal with an anti-tarnish finish, so they stay bright and gentle on sensitive ears." },
    ],
  },

  bali: {
    tier: 2,
    metaTitle: "Bali Earrings for Women | Pearl Bloom",
    metaDescription:
      "Shop bali earrings for women at Pearl Bloom — textured traditional hoops in lightweight, anti-tarnish gold-tone for daily and festive wear. Buy online.",
    primaryKeyword: "bali earrings",
    secondaryKeywords: ["bali earrings for women", "gold bali", "traditional bali earrings", "oxidised bali"],
    h1: "Bali Earrings for Women",
    lede: "Textured, ridged traditional hoops — earthy, ornamental and endlessly wearable.",
    heroAlt: "Pearl Bloom textured gold-tone bali hoop earrings on a cream background",
    assignedBlog: "types-of-earrings-guide",
    intro: [
      "Bali earrings are the textured, ridged hoops beloved across generations of Indian jewellery. Earthy, ornamental and endlessly wearable, they bring a traditional touch that still feels current — the everyday ethnic hoop. Pearl Bloom reimagines the bali in lightweight, anti-tarnish metal, so the heritage look comes with modern, all-day comfort.",
      [
        "Sitting where the ",
        { text: "hoop", href: "/earrings/style/hoop" },
        " meets traditional craft, balis pair effortlessly with kurtis, saris and fusion outfits alike. For a deeper ethnic mood, our ",
        { text: "oxidised", href: "/earrings/finish/oxidised" },
        " balis carry an antique finish, while gold-tone versions keep things bright. They love a ",
        { text: "festive", href: "/earrings/occasion/festive-wear" },
        " outing but are simple enough for daily devotion, and sit beautifully alongside traditional ",
        { text: "jhumka", href: "/earrings/style/jhumka" },
        " earrings.",
      ],
      "Skin-safe and hypoallergenic, with secure closures and a tarnish-resistant finish, balis are made to be worn often. Keep them dry and give them an occasional wipe to maintain the textured shine.",
    ],
    internalLinks: [
      { label: "Hoop Earrings", href: "/earrings/style/hoop" },
      { label: "Oxidised", href: "/earrings/finish/oxidised" },
      { label: "Jhumka Earrings", href: "/earrings/style/jhumka" },
      { label: "Festive Wear", href: "/earrings/occasion/festive-wear" },
    ],
    faqs: [
      { q: "What are bali earrings?", a: "Bali earrings are textured, ridged hoop earrings rooted in Indian tradition. They are ornamental yet everyday-wearable, available in bright gold-tone and antique oxidised finishes." },
      { q: "Can I wear bali earrings daily?", a: "Yes. Smaller balis are light and comfortable for daily wear with kurtis and casual outfits, while larger or oxidised pairs suit festive occasions." },
      { q: "What outfits suit bali earrings?", a: "Balis pair beautifully with ethnic and fusion outfits — kurtis, saris and indo-western looks — and oxidised versions work well with boho styles too." },
      { q: "Are bali earrings anti-tarnish and skin-safe?", a: "Yes. They use skin-safe, hypoallergenic metal with an anti-tarnish finish, so they stay bright and gentle on the ears with regular wear." },
    ],
  },
};
